### ISSUE TITLE
Missing docs

### ISSUE THREAD

**Issue by arikarim** [basecamp/kamal#1002]
One of the big issues is that the docs does not mention pushing the code to github.

Currently if you do any changes locally, redeploying with kamal does not have any effect, you have to push to github because kamal will fetch the code from github.

Please mention this in the docs.

**Comment by mike-weiner** [comment]
The docs already note this. See https://kamal-deploy.org/docs/configuration/builders/#build-context

> If this is not set, then a local git clone of the repo is used. This ensures a clean build with no uncommitted changes.
To use the local checkout instead you can set the context to ., or a path to another directory.

**Comment by arikarim** [comment]
Thanku
