### ISSUE TITLE
failed to read dockerfile: open Dockerfile: no such file or directory with Kamal 2 and Rails 8 template

### ISSUE THREAD

**Issue by intik** [basecamp/kamal#1012]
Hi,

I´m trying simple deploy of base app with Kamal 2 and Rails 8 template.

When running `kamal deploy -v` in app folder I see some success steps of login on my machine, login on host machine, checking/installing docker on host, cloning of app into local tmp directory. Last successful command is `docker buildx inspect kamal-local-docker-container`. 

Then it runs command `docker buildx build --push --platform linux/amd64 --builder kamal-local-docker-container -t xxx/xxx:xxx -t xxx/xxx:latest --label service="xxx" --file Dockerfile .` which fails with:

```
#0 building with "kamal-local-docker-container" instance using docker-container driver
#1 [internal] load build definition from Dockerfile
#1 transferring dockerfile: 2B done
#1 DONE 0.0s
ERROR: failed to solve: failed to read dockerfile: open Dockerfile: no such file or directory
```

I checked both the origin app directory and the `/tmp/kamal-clones/xxx/` directory and both are containing the same `Dockerfile` file.

Could it be because of some wrong configuration or a bug? 

Thanks

**Comment by gorbulls456667** [comment]
I get the same error when running `kamal setup` for a Dockerized Next.js application.  `failed to read dockerfile: open Dockerfile: no such file or directory`

```
#2 [internal] load build definition from Dockerfile
#2 transferring dockerfile: 2B 0.0s done
#2 DONE 0.1s
ERROR: failed to solve: failed to read dockerfile: open Dockerfile: no such file or directory
```

When I run `docker build -t nextjs-docker .` and then `docker run -p 3000:3000 nextjs-docker` it works fine locally. But I get this error when I run` kamal setup`: `ERROR: failed to solve: failed to read dockerfile: open Dockerfile: no such file or directory`

**Comment by djmb** [comment]
@gorbulls456667 - have you committed the Dockerfile? @intik - I guess you probably have if it's in `/tmp/kamal-clones/xxx/`.

Could you run `kamal build remove` and try again? That will remove and recreate the builder.

**Comment by gafrom** [comment]
Same issue for me.

When running `kamal setup` it fails with
```
  INFO [c2cd29de] Running docker buildx build --push --platform linux/amd64 --builder kamal-local-docker-container -t ghcr.io/moo/hru-app:47a5d9b23a82d8d48220fe6dce1c2d93deb39ca7 -t ghcr.io/moo/hru-app:latest --label service="moo-hru-app" --file Dockerfile . as oleg@localhost
 DEBUG [c2cd29de] Command: docker buildx build --push --platform linux/amd64 --builder kamal-local-docker-container -t ghcr.io/moo/hru:47a5d9b23a82d8d48220fe6dce1c2d93deb39ca7 -t ghcr.io/moo/hru:latest --label service="moo-hru-app" --file Dockerfile .
 DEBUG [c2cd29de] 	#0 building with "kamal-local-docker-container" instance using docker-container driver
 DEBUG [c2cd29de] 	
 DEBUG [c2cd29de] 	#1 [internal] load build definition from Dockerfile
 DEBUG [c2cd29de] 	#1 transferring dockerfile: 2B done
 DEBUG [c2cd29de] 	#1 DONE 0.0s
 DEBUG [c2cd29de] 	ERROR: failed to solve: failed to read dockerfile: open Dockerfile: no such file or directory
```

However, when running the same command outside of kamal - it works:
```
docker buildx build --push --platform linux/amd64 --builder kamal-local-docker-container -t ghcr.io/moo/hru-app:47a5d9b23a82d8d48220fe6dce1c2d93deb39ca7 -t ghcr.io/moo/hru-app:latest --label service="moo-hru-app" --file Dockerfile .
[+] Building 3.8s (3/3) FINISHED                                                docker-container:kamal-local-docker-container
 => [internal] load build definition from Dockerfile                                                                     0.0s
 => => transferring dockerfile: 2.23kB                                                                                   0.0s
 => resolve image config for docker-image://docker.io/docker/dockerfile:1 
```

**Comment by araujogui** [comment]
I had the same problem, comitting the `Dockerfile` solved it.

**Comment by Aevin1387** [comment]
For those coming on this same issue in the future, and not solving the issue with committing the `Dockerfile`. I was trying to run on my ubuntu 24.04 dev laptop, and it seems this can happen if you have `docker` installed via `snap`. I uninstalled the snap and installed `docker` as an apt package, and that fixed the issue.
