### ISSUE TITLE
Kamal Alias for MacOS points to 1.9.1

### ISSUE THREAD

**Issue by robertritz** [basecamp/kamal#1014]
I just tried upgrading a site to Kamal 2.0 and the alias in the documentation points to an image with 1.9.1. Are there updated images?

```
alias kamal='docker run -it --rm -v "${PWD}:/workdir" -v "/run/host-services/ssh-auth.sock:/run/host-services/ssh-auth.sock" -e SSH_AUTH_SOCK="/run/host-services/ssh-auth.sock" -v /var/run/docker.sock:/var/run/docker.sock ghcr.io/basecamp/kamal:latest'
```

**Comment by jeremy** [comment]
The `latest` tag is lagging, indeed, because 1.9.1 was pushed more recently. /cc @djmb 

Use the [v2.0.0](https://github.com/basecamp/kamal/pkgs/container/kamal/280187025?tag=v2.0.0) tag for now.

**Comment by robertritz** [comment]
Gotcha!
