### ISSUE TITLE
Expose `pause` and `resume` proxy option in Kamal

### ISSUE THREAD

**Issue by baldarn** [basecamp/kamal#1046]
Hi! based on issues https://github.com/basecamp/kamal-proxy/issues/4 and comments https://github.com/basecamp/kamal-proxy/issues/4#issuecomment-2354231228 https://github.com/basecamp/kamal-proxy/issues/8#issuecomment-2354236607

I would like to have the exposure of `pause` and `resume` methods of `kamal-proxy`

**Comment by dhh** [comment]
We are going to tweak these, then expose.
