### ISSUE TITLE
[Kamal 2] Automatic Proxy Reboot

### ISSUE THREAD

**Issue by irfanfadilah** [basecamp/kamal#1055]
I keep getting this error after deploying with `kamal deploy --skip-push`:

```
ERROR (RuntimeError): Exception while executing on host xxx.xxx.xxx.xxx: kamal-proxy version v0.6.0 is too old, please reboot to update to at least v0.7.0
```

Do we need to manually run `kamal proxy reboot` every time the proxy needs reboot? But it is doesn't seem very convenient.

Is it possible to make `kamal deploy` command to also reboot the proxy when it is necessary?

---

EDIT: I also noticed that if we don't update the gem, running `kamal proxy reboot` won't update the proxy. We have to update the gem and then run the reboot command again. In my case, this happens because I build the image using GitHub Actions and push it to the GitHub Container Registry, then in my workflow, I only call `kamal deploy --skip-push`.

**Comment by dhh** [comment]
Rebooting the proxy means there's a gap in deployment. That shouldn't just happen automatically as a side effect to normal deployment. Some folks might want to time that with a lull in their traffic. So I consider the approach as we have it now correct.

Proxy only needs rebooting when it's upgraded. When that's required, it'll be a manual step.
