### ISSUE TITLE
Potential issue with lpass adapter on a Mac?

### ISSUE THREAD

**Issue by afgallo** [basecamp/kamal#1089]
I've got `lpass` installed via Homebrew on a Mac. I run kamal with the docker alias. Here is what happens when I try to run `kamal secrets fetch --adapter lastpass --account email@example.com --from MyFolder`.

![image](https://github.com/user-attachments/assets/7f0f6389-aaf6-451e-a4cd-e0f65d6c6454)

As you can see in the image above, I do have `lpass` installed. Is there anything I am doing wrong here? I took a peak at the code and there is nothing unusual, just a regular call to `lpass` [here](https://github.com/basecamp/kamal/blob/3654a7e1be35764be8bc66f4e6e0fad5a549eb01/lib/kamal/secrets/adapters/last_pass.rb#L5)

Any help is appreciated, thank you!

**Comment by tuladhar** [comment]
@afgallo This is a known issue when running Kamal with the docker alias, check this issue https://github.com/basecamp/kamal/issues/1065

**Comment by afgallo** [comment]
Thanks @tuladhar, sorry I've missed #1065 before creating this one.
