### ISSUE TITLE
Stable container name for the web service

### ISSUE THREAD

**Issue by miharekar** [basecamp/kamal#1091]
Use case: I'd like to connect from Prometheus to my web service without going through the internet.

I can connect to other accessories like `[service-name]-cadvisor:9200` but `[service-name]-web:80` goes through Kamal Proxy and that one rejects it, because it doesn't recognize the host.

The actual container name of the web service changes with each deploy, so I can't really hardcode it in prometheus' config.yml.

Any other suggestions you might have of how I might achieve that?

**Comment by askadityapandey** [comment]
Docker network alias, umm could be a good one?

**Comment by djmb** [comment]
We run `otel_collector` as an accessory and connect prometheus to it. The collector is configured to pick up the app containers using docker discovery.

There's more info here - https://dev.37signals.com/kamal-prometheus/

**Comment by jonasbark** [comment]
I'm really not sure why this ticket was closed, as I've got the same issue and I don't think this is properly covered.

` docker network inspect kamal` will indeed tell you which endpoint can be used:
```
...
"f490b65d1ab7622c6a307c50a8a5144db41a55c3343582685c8726f5322de97d": {
                "Name": "cloudconnect-web-efd125f9a55a6f33627761e48ddf907031ee16bb",
...
```
but as @miharekar noted that name will change with each git commit. 

```
docker network disconnect kamal f490b65d1ab7622c6a307c50a8a5144db41a55c3343582685c8726f5322de97d
docker network connect --alias cloudconnect kamal f490b65d1ab7622c6a307c50a8a5144db41a55c3343582685c8726f5322de97
```
Will work indeed, but I have not seen this option exposed.

**Comment by huseyin** [comment]
I ran into the same issue when setting up Prometheus without otel collector and solved it adding a post-deploy hook that adds an alias on every deploy (something similar to @jonasbark's approach). That said, I don’t think this case is unique to Prometheus. We could be emitting anything through any port with a listener consuming it, and in all those cases, we should be able to connect to the container using a stable hostname. Having an option to add aliases right in the config would indeed be good.

**Comment by pjpires** [comment]
> An example post-deploy hook:
> 
> ```shell
> CONTAINER_ID=$(kamal server exec -q docker ps --filter "ancestor=ghcr.io/..." --format "{{.ID}}" | tail -n +2)
> echo "Container ID: $CONTAINER_ID"
> kamal server exec docker network disconnect kamal "$CONTAINER_ID";
> kamal server exec docker network connect --alias cloudconnect kamal "$CONTAINER_ID";
> ```

@jonasbark this was super useful for me to be able to get an "accessory" (anycable-go) to connect with a service (RPC) running as a "server" (in kamal's terms), thank you very much! 🙏 

However, in the end I think I found a simpler solution, so I'll leave it here in case someone finds it useful. Since kamal forwards the `options:` to the underlying `docker run ...` command, I was able to do this:

```yml
servers:
  anycable-rpc:
    host: <%= ENV['HOST'] %>
    options:
      network-alias: my-app-anycable-rpc

accessories:
  anycable-go:
    # ... other configs
    env:
      clear:
        ANYCABLE_RPC_HOST: "my-app-anycable-rpc:50051"
```

Note: I initially tried the [`name`](https://docs.docker.com/reference/cli/docker/container/run/#name) option instead, it's still forwarded to `docker run` but would make kamal fail in a subsequent `docker container ls` command as it is expecting to find the container by a different name.

**Comment by junket** [comment]
@pjpires Good stuff! For clarity, your approach works only if the server and accessory share the same host, yes? I'm trying to figure out how to get kamal-deployed containers talking to each other when on different hosts... and without kamal-proxy complaining about exposed ports it doesn't manage 🧐

**Comment by pjpires** [comment]
> [<img alt="" width="16" height="16" src="https://avatars.githubusercontent.com/u/1846767?v=4&amp;size=80">@pjpires](https://github.com/pjpires) Good stuff! For clarity, your approach works only if the server and accessory share the same host, yes? I'm trying to figure out how to get kamal-deployed containers talking to each other when on different hosts... and without kamal-proxy complaining about exposed ports it doesn't manage 🧐

Yes, I should have made that clearer. This works if both the server and accessory are running on the same host. 

[This issue](https://github.com/basecamp/kamal/issues/1278) revisits the discussion on stable names for server containers, which seems to be currently under consideration. You might want to subscribe it for updates.
