### ISSUE TITLE
Kamal 2 on Digital Ocean and Cloudflare

### ISSUE THREAD

**Issue by mooktakim** [basecamp/kamal#1096]
I'm trying to setup rails app with kamal 2 on digital ocean.
I have it all setup and app starts. I'm using thruster and kamal proxy.
I can visit the app server directly, works correctly.

The issue I have is with using a load balancer on digital ocean. I want to be able to run multiple app servers and have them behind DO load balancer.

I have the DO LB setup to forward HTTP and HTTPS with passthrough, on the usual ports.
I think the issue I'm facing is the LB's health checks are not responded to by kamal-proxy. I believe the proxy is only responding when the hostname matches the `deploy.yml` file. I don't see any requests being made on kamal logs. The LB droplet is always "down". 
Is there a way to set kamal-proxy "default" hostname?

My setup is this:
cloudflare -> DO LB -> kamal-proxy

I could turn off kamal-proxy, but then I won't be able to have SSL on the LB as DO requires me to move my domain DNS to DO. But I want to keep DNS on cloudflare.

What is the solution here?

**Comment by dhh** [comment]
Make sure you have `config.assume_ssl` set and that you have `proxy: false` in the config/deploy.yml. That'll ensure you can terminate SSL at Cloudflare, and the DO LB can hit /up for healthcheck without problems. The proxy with SSL/host termination/routing is only applicable when you're dealing with a single server.

**Comment by mooktakim** [comment]
Terminating SSL at cloudflare isn't the issue. The issue is the DO LB doesn't do healthcheck correctly with the apps because it doesn't provide hostname to hit the `/up` endpoints. It never enables those target servers. 
A good solution could be to allow kamal-proxy to direct traffic to a "default" app when host is not provided.

**Comment by mooktakim** [comment]
The only solution I have right now is not to use DO LB. Instead, use Cloudflares load balancer, which sends traffic in only HTTPS directly to the application servers.
