### ISSUE TITLE
Getting `ERROR (SSHKit::Command::Failed): docker exit status: 256` on `kamal setup`

### ISSUE THREAD

**Issue by yonas-g** [basecamp/kamal#1098]
When I do `kamal setup,` I get `ERROR (SSHKit::Command::Failed): docker exit status: 256`.

Here is the full error message

```bash
ERROR (SSHKit::Command::Failed): docker exit status: 256
docker stdout: Nothing written
docker stderr: ERROR: failed to initialize builder kamal-local-docker-container (kamal-local-docker-container0): permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.46/containers/buildx_buildkit_kamal-local-docker-container0/json": dial unix /var/run/docker.sock: connect: permission denied
```

I have also tried manually adding the `$USER` to the docker group but the error still persists.

**Comment by erichstark** [comment]
Do you have your local docker up and running?

**Comment by yonas-g** [comment]
Thanks! This solved the issue!

**Comment by KlausSchaefers** [comment]
I was logged into docker desktop, but had used a token for Kamal. This also caused an issue. Logging out solved the issue.

**Comment by KlausSchaefers** [comment]
For me it would be ok, to have just use the docker desktop user. I tried removed the username and password section from the docker desktop
