### ISSUE TITLE
Error: kamal-proxy version v0.8.0 is too old

### ISSUE THREAD

**Issue by zaddy6** [basecamp/kamal#1103]
Is there a way to stop breaking changes like this, for example my CI/CD that has been working suddenly failed because I needed to upgrade kamal-proxy, we should have a way to control things like this from happening 

```
  INFO [f4300e4d] Finished in 0.245 seconds with exit status 0 (successful).
Ensure kamal-proxy is running...
  INFO [648fc2f9] Running docker network create kamal on 5.78.**.**
  INFO [1182e3a8] Running docker login ghcr.io -u [REDACTED] -p [REDACTED] on 5.78.**.**
  INFO [1182e3a8] Finished in 0.543 seconds with exit status 0 (successful).
  INFO [c470fb96] Running docker inspect kamal-proxy --format '{{.Config.Image}}' | cut -d: -f2 on 5.78.**.**
  INFO [c470fb96] Finished in 0.242 seconds with exit status 0 (successful).
  Finished all in 43.2 seconds
Releasing the deploy lock...
  Finished all in 44.7 seconds
  ERROR (RuntimeError): Exception while executing on host 5.78.**.**: kamal-proxy version v0.8.0 is too old, please reboot to update to at least v0.8.1
Error: Process completed with exit code 1.
```

**Comment by taher-tigerlab** [comment]
I think this can be controlled by specifying Kamal version on your cicd tool
If you used an older version to set it up and are using `latest` in your cicd tool it will upgrade once a new image is pushed to the `latest` tag

**Comment by tuladhar** [comment]
Yes, always pin the Kamal version in your CI/CD otherwise to avoid this.

**Comment by yonas-g** [comment]
How do you pin a specific version?

**Comment by dhh** [comment]
You can pin a specific version in your Gemfile, if using on a Ruby project, or tie to a specific image version if using the docker alias: https://github.com/basecamp/kamal/pkgs/container/kamal.
