### ISSUE TITLE
Error reading secrets from a Bitwarden item

### ISSUE THREAD

**Issue by fidalgo** [basecamp/kamal#1134]
`SECRETS=$(kamal secrets fetch --adapter bitwarden --account aaaaa@-------.pt --from kamal REGISTRY_PASSWORD)`

```
 kamal secrets extract kamal/REGISTRY_PASSWORD $SECRETS
  ERROR (JSON::ParserError): unexpected token at '\{\"kamal/REGISTRY_PASSWORD\":\"ghp_--------------------------v\"\}'
  ```
  and even with `"`
  ```
 kamal secrets extract "kamal/REGISTRY_PASSWORD" $SECRETS
  ERROR (JSON::ParserError): unexpected token at '\{\"kamal/REGISTRY_PASSWORD\":\"ghp_--------------------------v\"\}'
  ```

Note: email and tokens redacted for obvious reasons

 Am I missing something from the docs? In Bitwarden, I just created a new item called `kamal` and added the `REGISTRY_PASSWORD` as a custom field with a given value.

**Comment by alanoliveira** [comment]
I had exactly the same issue a few days ago.
Are you running these commands directly on the shell (like I was doing)?

Kamal is using the [dotenv gem](https://github.com/bkeepers/dotenv) to parse the `secrets` file.
If you want to run it in the shell you need to create the `secrets` file and use the `dotenv` binary to get the right values
For example
``` 
dotenv -f .kamal/secrets 'echo $SECRETS'
```

The [docs](https://kamal-deploy.org/docs/configuration/environment-variables/#secrets) kind of mention it, but it's quite unclear.
> Kamal uses dotenv to automatically load environment variables set in the .kamal/secrets file.

**Comment by markschuh** [comment]
RF

**Comment by fidalgo** [comment]
Yes, I was! 
I was battling Bitwarden, between items, folders and vaults and try to find out would work.

So if you come here, with the same problem, you just need to create an item in Bitwarden and under `CUSTOM FIELDS` add your secrets by `NAME` and `VALUE` , then you can use `--from YOUR_ITEM_NAME`
