### ISSUE TITLE
Proposal: Omit item name from the JSON on secrets fetch

### ISSUE THREAD

**Issue by fidalgo** [basecamp/kamal#1135]
I'm playing around with Kamal and Bitwarden and I stumbled on this and had to double read the docs.

When fetching an item from an Item in Bitwarden, the JSON key, brings that item path:
`kamal secrets fetch --adapter bitwarden --account aaaaaa@-------.pt --from kamal REGISTRY_PASSWORD`

`\{\"kamal/REGISTRY_PASSWORD\":\"ghp_--------------------------v\"\}`

Given we're instructing to read the secrets from a given item in Bitwarden, can we omit it from the result?
I'm talking here about just the ergonomics, if I instruct reading X from Y location, I usually only care about the data, not about the source.

So, what do you guys think about omitting the path in the result?

**Comment by djmb** [comment]
@fidalgo - if you use `kamal secrets extract` to grab the password from the JSON, it will work if you specify `REGISTRY_PASSWORD` or `kamal/REGISTRY_PASSWORD`.

**Comment by fidalgo** [comment]
That is absolutely correct, I was fighting my way into Bitwarden and end up running the commands in the command line, expecting the sequence to be exactly what is shown on docs. But I missed the fact we use `dotenv` to parse the output.

**Comment by nerijunior** [comment]
@fidalgo, sorry for reviving this topic, but what is `--from kamal`? I'm trying to use a folder inside my "root" vault in Bitwarden, but I only see a `Not found` error.

**Comment by fidalgo** [comment]
@nerijunior I cannot exactly remember it, I was fighting to get my credentials from bitwarden at the time... I guess I was trying to replicate the internal commands kamal does when fetchting.
Now for [Reviato](https://www.reviato.com) I use a custom parser from rails credentials, using `yq`. When I upgrade my stack to rails 8.1 will use the new credentails:fetch: https://guides.rubyonrails.org/8_1_release_notes.html#command-line-credentials-fetching

**Comment by nerijunior** [comment]
Thanks @fida. I gave up and switched to Bitwarden password manager.
