### ISSUE TITLE
Fastcgi support for kamal

### ISSUE THREAD

**Issue by lado936** [basecamp/kamal#1145]
Hi, i am trying to setup kamal for php based app, which is running fpm, as it uses fastcgi protocol kamal-proxy is unable to connect to it and health checks are failing with error "read: connection reset by peer". Is there any plan to support fastcgi, or the only workaround is to use nginx in front of it? It will be quite disappointing to have set up proxy in front of nginx in front of api

**Comment by djmb** [comment]
Hi @lado936, I don't think we'd be likely to add fastcgi support. Sorry!

**Comment by lado936** [comment]
Sorry but closing issue straight away is not a solution, as I understand you are advertising kamal as simple solution for any kind of workload, is there any workaround we can use kamal with fpm based apps? I checked other issues and you mention that disabling proxy at all is not what kamal 2 is designed for. How can i solve it then?

**Comment by djmb** [comment]
@lado936 - I think you'll need to run NGINX or something other proxy that speaks FastCGI in your application's container and then have that talk to kamal-proxy.

kamal-proxy is not designed to be a general purpose proxy, it's there to support Kamal features like zero-downtime deployments.

**Comment by lado936** [comment]
its quite an overhead to have loadbalancer->kamal-proxy->nginx->app, can i disable kamal-proxy at all and kust use nginx in front with fastcgi?

**Comment by djmb** [comment]
> its quite an overhead to have loadbalancer->kamal-proxy->nginx->app

Do you mean a performance overhead? I'd be surprised if there was a noticeable difference in request times compared to the cost of serving the requests over the internet (assuming that's what you are doing). Though that's just a guess on my part!

It is a more complex setup, that's true but I'm afraid it's the only route right now. Kamal requires kamal-proxy for zero-downtime deployment of web apps and there's no plan to add FastCGI support at the moment.

**Comment by lado936** [comment]
Not performance exactly, but just debugging side, if something goes wrong there is more moving part you have to check whats wrong, but i get your view also, will try with nginx, thanks for your input
