### ISSUE TITLE
SSH config property doesn't allow custom path 

### ISSUE THREAD

**Issue by GideonStowell** [basecamp/kamal#1161]
I am finding that the ssh/config property for my kamal 2.2.2 deployment doesn't actually support a custom ssh config path as [described in the documentation](https://kamal-deploy.org/docs/configuration/ssh/#config).

```
# deploy.yml
ssh:
  user: ubuntu
  proxy: ubuntu@bastion
  config: ./sshconfig 
 ```

```
# ./sshconfig
host bastion
     HostName i-000000000000000
     IdentitiesOnly yes
     IdentityFile ~/.ssh/id_ed25519
     ProxyCommand sh -c "aws ssm start-session --target %h --document-name AWS-StartSSHSession --region=us-west-2"
```

`kamal details` output:
```
ERROR (Kamal::ConfigurationError): ssh/config: should be a boolean
```

The docs clearly say that this property defaults to true to load the default OpenSSH config files, but can be set "to a file path (or array of paths) to load specific configuration". I am trying to set it to a path, but as you can see in the attached error log, it is not valid configuration.

Are there any examples of how to do this correctly?

**Comment by jeremy** [comment]
Check out #1129

**Comment by GideonStowell** [comment]
Thanks for finding that PR. I'd be very interested in this functionality being available soon. @jeremy are you able to help me finding someone to review and bring that change in?
