### ISSUE TITLE
missing option `deploy_timeout` from documentation 

### ISSUE THREAD

**Issue by BelalAEzzat** [basecamp/kamal#1176]
I suffered from failed deployment for weeks until I read this book. Kamal Handbook The Missing Manual by Josef Strzibny. Where he documents this option. That I am sorely lacking. also [searching](https://kamal-deploy.org/docs/search/?q=deploy_timeout) doesn't return any result.

**Comment by djmb** [comment]
It is in the docs here - https://kamal-deploy.org/docs/configuration/overview/#deploy-timeout.

It doesn't show up in the search as you said - we need to look at the tokenisation of search terms on docs site.
