### ISSUE TITLE
Add command to list deployments with commit id and/or commit message

### ISSUE THREAD

**Issue by ACPK** [basecamp/kamal#1182]
How can recent deployments be listed including the commit ID and message for each? This feature would streamline deployment tracking by displaying essential commit details in a single view.

**Comment by djmb** [comment]
@ACPK - are you using Github? If so you could call something like this to a post deploy hook:

```
#!/usr/bin/env bash

gh release create $KAMAL_SERVICE_VERSION --target $KAMAL_VERSION --generate-notes 2> /dev/null || true
```

The you can view the releases in the Github UI.

You probably want to gate it based on the branch and destination though if you deploy to multiple ones.

Kamal doesn't contain release tracking itself though and there are no plans to add it, right now anyway.
