### ISSUE TITLE
Expand or rename secrets

### ISSUE THREAD

**Issue by daanlenaerts** [basecamp/kamal#1203]
When setting up a Kamal project with two accessories: a Postgres database and a Pgbouncer accessory, I ran into a scenario where the Postgres container expects a `DB_PASSWORD` secret, where the Pgbouncer container expects a `POSTGRES_PASSWORD` secret.

My current solution is to set both in the secrets file:
```
DB_PASSWORD=1234
POSTGRES_PASSWORD=1234
```

Is there any way to expand or rename those secrets in the deploy.yml file such that is not necessary to repeat the same password twice in the secrets file?

**Comment by vldmr-k** [comment]
You can use 
```
DB_PASSWORD=1234
POSTGRES_PASSWORD=$DB_PASSWORD
```
