### ISSUE TITLE
Hooks should be able to have access to the config

### ISSUE THREAD

**Issue by jcoyne** [basecamp/kamal#1207]
In my case I need the ssh username in the pre-connect hook.

This allows my pre-connect hook to put a temporary key on the remote server. I have to do this because we use GSS-API/Kerberos for auth, but there is no support for that in net-ssh.

I'm basically porting this code for capistrano into a Kamal hook: https://github.com/cbeer/capistrano-one_time_key/blob/master/lib/capistrano/one_time_key.rb

**Comment by 3v0k4** [comment]
Have you considered something like the following?

```
#!/usr/bin/env ruby

require 'yaml'

config = File.read(File.join(Dir.pwd, "config", "deploy.yml"))
ssh_user = YAML.load(config).dig("ssh", "user")
puts ssh_user
```

**Comment by jcoyne** [comment]
@3v0k4 that would work. It seemed inelegant, but maybe it doesn't matter to have two copies of the config loaded.

**Comment by 3v0k4** [comment]
The thing is that, with the current architecture, hooks are run in a separate process that runs the script.

An alternative you could consider is:

```
#!/usr/bin/env ruby

require 'open3'

config, _status = Open3.capture2('kamal config')
ssh_user = YAML.load(config).dig(:ssh_options, :user)
puts ssh_user
```

**Comment by jcoyne** [comment]
Thank you for the suggestions.
