### ISSUE TITLE
missing dependency: erb

### ISSUE THREAD

**Issue by thelittlebug** [basecamp/kamal#1212]
thank you for your wonderful project.
after playing around with it in a docker shell i'm convinced to try it in rl.

but on a fresh install, after installing ruby 3.3.5 via `pacseek` and kamal via `gem install kamal` im not able to run kamal

after manually installing erb via `gem install erb` its working.
i've looked in the gem spec file, and there is no erb package specified.

maybe makes sense because every rails developer already has erb (im pretty sure i know thats a webserver, so rails maybe use it) in his ruby env so no one noticed this little issue.

**Comment by 3v0k4** [comment]
I think the idea is to [support Ruby >=3.x](https://github.com/basecamp/kamal/commit/e160852e4d87a4bc066309c5b240c29e16548dec) in Kamal.

`erb` is a [standard gem since ruby 3.0](https://stdgems.org/), so there's no need to install it separately.

> but on a fresh install, after installing ruby 3.3.5 via pacseek and kamal via gem install kamal im not able to run kamal
This should not happen 🙂

**Comment by thelittlebug** [comment]
thank you for your clarification. that seams strange.

now i know that erb is a template language ^^ (im neither a rails nor a ruby developer)
i will try to reproduce this issue with a clean install of arch linux.
with that i should be able to find out whats wrong. it could either be:
1. the arch pkg ruby
2. my individual setup. maybe theres something wrong with the system gem pkg path. who knows
3. the current planet constellation issued a bit flip somewhere on my system :D

thx, i will try to find that out

**Comment by thelittlebug** [comment]
ok, it seems the ruby pkg isn't requiring the ruby-erb pkg according to https://archlinux.org/packages/extra/x86_64/ruby/

**Comment by thelittlebug** [comment]
for future non rails/ruby people using arch:

there is a default pkg for ruby :)
https://archlinux.org/packages/extra/x86_64/ruby-default-gems/
