### ISSUE TITLE
Unable to disable proxy with `proxy: false`

### ISSUE THREAD

**Issue by scomma** [basecamp/kamal#1217]
Per documentation:

> The proxy is configured in the root configuration under proxy. These are options that are set when deploying the application, not when booting the proxy.
> They are application-specific, so they are not shared when multiple applications run on the same proxy.
> The proxy is enabled by default on the primary role but can be disabled by setting proxy: false.

This doesn't work, because the code that actually disables the proxy lives in `Kamal::Configuration::Role#initialize_specialized_proxy`, and it only takes role proxy configuration into account, not the top-level root configuration.

As a workaround, you can disable the proxy in `servers`:

```
servers:
  web:
    hosts:
      - 192.168.0.1
    proxy: false
```

**Comment by claasz** [comment]
See also https://github.com/basecamp/kamal/issues/1133#issuecomment-2429097515 and https://github.com/basecamp/kamal/issues/1133#issuecomment-2548971210

**Comment by scomma** [comment]
> See also [#1133 (comment)](https://github.com/basecamp/kamal/issues/1133#issuecomment-2429097515)

He's right. I've given in to using Kamal the way it's intended; much easier that way. The proxy doesn't add any noticeable latency and is an essential component for zero-downtime deploys.

I'm closing this issue so it doesn't clutter up the project.
