### ISSUE TITLE
Unable to run newer kamal-proxy release

### ISSUE THREAD

**Issue by AxelTheGerman** [basecamp/kamal#1252]
It looks like the "minimum" proxy version is indeed hard coded to a specific one.

https://github.com/basecamp/kamal/blob/74960499c053c0e0790f039b6f139ed46b3250cb/lib/kamal/configuration.rb#L265

https://github.com/basecamp/kamal/blob/74960499c053c0e0790f039b6f139ed46b3250cb/lib/kamal/configuration.rb#L17

Would it be possible to somehow run a newer proxy version or is it by design that the gem and proxy get upgraded together - meaning each proxy bump requires a gem bump as well?

Reason I'm asking is that there might be features in the proxy which are maybe not required for all kamal users but something I'd like to deploy to my apps already.

**Comment by AxelTheGerman** [comment]
E.g. latest release `0.8.3` brings improvements and fixes minor issues but maybe shouldn't force all kamal users to reboot the proxy - https://github.com/basecamp/kamal-proxy/releases/tag/v0.8.3

**Comment by morgoth** [comment]
@AxelTheGerman since https://github.com/basecamp/kamal/pull/1253 was merged, can you close the issue?

**Comment by AxelTheGerman** [comment]
Yes, happy to close it.

Though when proxy reaches 1.0 we might want some versioning that allows running all minor and patch versions of a major version (maybe enforcing a minimum version).

Happy to revisit when the time comes though and not add that complexity yet.
