### ISSUE TITLE
Old Dockerfile being used during build

### ISSUE THREAD

**Issue by michaelcarter** [basecamp/kamal#1262]
Using Kamal 2.3.0, I’ve updated the Dockerfile (Rails default) for my project, so instead of: 

```
FROM registry.docker.com/library/ruby:$RUBY_VERSION-slim AS base
```

It’s now using the `slim-bullseye` image as base:

```
FROM registry.docker.com/library/ruby:$RUBY_VERSION-slim-bullseye AS base
```

However, when I run `kamal deploy`, it still appears to be building using the old Dockerfile (see last line):

```
ERROR (SSHKit::Command::Failed): docker exit status: 256
docker stdout: Nothing written
docker stderr: #0 building with "kamal-local-docker-container" instance using docker-container driver

#1 [internal] load build definition from Dockerfile
#1 transferring dockerfile: 1.92kB done
#1 DONE 0.0s

#2 resolve image config for docker-image://docker.io/docker/dockerfile:1
#2 DONE 0.8s

#3 docker-image://docker.io/docker/dockerfile:1@sha256:865e5dd094beca432e8c0a1d5e1c465db5f998dca4e439981029b3b81fb39ed5
#3 resolve docker.io/docker/dockerfile:1@sha256:865e5dd094beca432e8c0a1d5e1c465db5f998dca4e439981029b3b81fb39ed5 done
#3 CACHED

#4 [internal] load metadata for registry.docker.com/library/ruby:3.3.6-slim
```

It’s probably a skill issue rather than a bug with Kamal, but I’ve bashed my head against this for a couple of hours, and I can’t figure out why this is happening. Any help anyone could offer would be much appreciated.

**Comment by sealabcore** [comment]
This seems to be docker cache related. Does it work if you clear the docker cache?

```
#3 docker-image://docker.io/docker/dockerfile:1@sha256:865e5dd094beca432e8c0a1d5e1c465db5f998dca4e439981029b3b81fb39ed5
#3 resolve docker.io/docker/dockerfile:1@sha256:865e5dd094beca432e8c0a1d5e1c465db5f998dca4e439981029b3b81fb39ed5 done
#3 CACHED
```

**Comment by aguynamedben** [comment]
I ran into this today. Try committing the Dockerfile to git, I think Docker uses git commit sha1 and caches when doing its magic.

**Comment by djmb** [comment]
Kamal builds from a local clone by default, so this would happen if you haven't committed the Dockerfile change.

**Comment by michaelcarter** [comment]
Thank you! Not having committed my changes was the issue. Ironically, I wanted to know they were working properly before they were committed. 😅
