### ISSUE TITLE
Dotenv 3.1.5 breaks kamal deploy

### ISSUE THREAD

**Issue by marciotoshio** [basecamp/kamal#1294]
Maybe not a kamal problem but I'd like to let people aware, my latest deploys were broken and seems like the culprit is the new version of dotenv.
```
ERROR (Kamal::ConfigurationError): Exception while executing on host x.x.x.x: Secret 'DATABASE_URL' not found in .kamal/secrets.staging
``` 
I installed the previous gem version `3.1.4` before installing kamal in the CI

**Comment by marciotoshio** [comment]
An issue is already open in dotenv repo https://github.com/bkeepers/dotenv/issues/518

**Comment by zaddy6** [comment]
How did you fix, this completely broke my entire CI/CD workflow

**Comment by marciotoshio** [comment]
Install dotenv pinned to the previous version before Kamal
```
gem install dotenv -v '3.1.4' 
gem install kamal
```

**Comment by frenkel** [comment]
@marciotoshio thanks for pointing this out! I have been debugging my Github Action the whole morning and finally came to the conclusion something in Kamal or it's dependencies was broken. Will lock dotenv for now.

**Comment by frenkel** [comment]
The issue is because https://github.com/bkeepers/dotenv/blob/962641232d379472af77908dfed3f2f0a5c234dc/lib/dotenv/parser.rb#L56 is executed for environment variables that are already set. Seems like Kamal is using it incorrectly somehow as it expected that to be replaced.

**Comment by frenkel** [comment]
@djmb thank you!

**Comment by AxelTheGerman** [comment]
Big +1, thank you `djmb` for this super quick resolution!
