### ISSUE TITLE
suggestion: failed traefik boot clean up

### ISSUE THREAD

**Issue by mcgaw** [basecamp/kamal#217]
My traefik container originally failed to start due to a port conflict on port 80. However this leaves a container lying around called `traefik` that then causes subsequent boots to fail (even though I had fixed the port conflict).

Perhaps failed boots of traefik should be cleaned up? Or is there some state issue I'm missing?

**Comment by dhh** [comment]
Would be nice to clean it up automatically, yeah. Please do investigate.
