### ISSUE TITLE
ERROR (Errno::ENOENT): No such file or directory - /usr/bin/env

### ISSUE THREAD

**Issue by caisilus** [basecamp/kamal#284]
For some reason when releasing the deploy lock after deploy this error occurs. I guess it's somehow connected with line endings: I am working on Windows and several times I had the same error because of CRLF instead of LF in files like bin/rails, bin/bundle, etc.

The same error occurs when I run mrsk setup on my Windows pc. On linux it seems to work without errors.

Here are mrsk logs:

```
Releasing the deploy lock
  INFO [37efe8e5] Running /usr/bin/env rm mrsk_lock/details && rm -r mrsk_lock on <my server ip>
  INFO [37efe8e5] Finished in 0.256 seconds with exit status 0 (successful).
  ERROR (Errno::ENOENT): No such file or directory - /usr/bin/env 
```
It doesn't prevent me from deploying actually

**Comment by caisilus** [comment]
> These commands are all run on a remote host. Are you trying to deploy to a Windows host? If so, that's not a use case we're supporting. But you should be able to run mrsk from a Windows machine against a 'nix host.

I am running it on a Windows machine against a 'nix host (Ubuntu 22.04 LTS in particular). And it works fine, but this error occurs in logs for some reason

**Comment by igor-alexandrov** [comment]
@caisilus do you still experience the issue?

**Comment by gerardnico** [comment]
Tried to skip the build and push with the `--skip-push` option without success because `kamal` adds an extra id to the image id.

Error:
```
INFO [7221f072] Running docker pull gerardnico/postgres:16.3.1:d2b370fb1a8cb71af1c04321fc815a0ffb843678 on 128.140.102.116
  Finished all in 4.8 seconds
  ERROR (SSHKit::Command::Failed): Exception while executing on host 128.140.102.116: docker exit status: 1
docker stdout: Nothing written
docker stderr: invalid reference format
```

**Steps and command**

```bash
# build and push with docker
# docker build apps/postgres/docker -t gerardnico/postgres:16.3.1
# docker push gerardnico/postgres:16.3.1
# then
kamal deploy -c apps/postgres/docker/config/deploy.yml --skip-push
```
```
Log into image registry...
  INFO [91017e8c] Running docker login -u [REDACTED] -p [REDACTED] as ngera@localhost
  INFO [91017e8c] Finished in 1.619 seconds with exit status 0 (successful).
  INFO [52070981] Running docker login -u [REDACTED] -p [REDACTED] on 128.140.102.116
  INFO [52070981] Finished in 2.407 seconds with exit status 0 (successful).
Pull app image...
  INFO [50b9babe] Running docker image rm --force gerardnico/postgres:16.3.1:d2b370fb1a8cb71af1c04321fc815a0ffb843678 on
 128.140.102.116
  INFO [50b9babe] Finished in 0.188 seconds with exit status 1 (failed).
  INFO [7221f072] Running docker pull gerardnico/postgres:16.3.1:d2b370fb1a8cb71af1c04321fc815a0ffb843678 on 128.140.102.116
  Finished all in 4.8 seconds
  ERROR (SSHKit::Command::Failed): Exception while executing on host 128.140.102.116: docker exit status: 1
docker stdout: Nothing written
docker stderr: invalid reference format
```

**Comment by picolino** [comment]
Got exactly same error when deploying from Windows machine

**Comment by picolino** [comment]
It seems like Kamal doesn't fully support many commands when you try to use it on a Windows machine. I see a lot of Unix-specific hardcode, like `/dev/null` or `/usr/bin/env`, which is definitely a breach in documentation that Windows is not supported for the current version of Kamal.

**Comment by gerardnico** [comment]
I switched to kubernetes (k3s with argocd) and I'm not going back. So good.

On Windows, installing wsl could be a solution.

**Comment by dhh** [comment]
I can highly recommend WSL. Makes life when working with Unix-based tools, like Kamal, much easier.

**Comment by randohinn** [comment]
Somehow, non-wsl worked for me in th emeantime, but this is back as of Kamal 2

**Comment by lostdev** [comment]
> Somehow, non-wsl worked for me in the meantime, but this is back as of Kamal 2.
> 
> In kamal 2, this can be avoided by setting
> 
> ```yaml
> builder:
>   context: .
> ```

Unfortunately did not work for me with Kamal-2.4.0.

Kamal seems awesome, but not being able to deploy from my windows box is a little painful. WSL would probably work, but it would be nice to have support native support if this is as simple as changing a few hardcoded paths!

**Comment by joshleblanc** [comment]
Removing the pre/post hooks and setting an explicit context worked for me, deploying on windows.
