### ISSUE TITLE
Large number of hosts causes connection failures

### ISSUE THREAD

**Issue by russ** [basecamp/kamal#326]
I found that when I go over a certain number of hosts, around 15 or so I think, all commands will fail with a `Connection reset by peer` error.

My config looks something like this, but with 50+ hosts.

```
servers:
  web:
    hosts:
      - 0.0.0.0
    cmd: /app/server
  worker:
    hosts:
      - 1.1.1.1
      - 2.2.2.2
      - 3.3.3.3
      - 4.4.4.4
      - ...
```

Anytime I run a command it fails.

```  
  INFO [832a85bb] Finished in 0.172 seconds with exit status 0 (successful).
  INFO [104317fa] Finished in 2.031 seconds with exit status 0 (successful).
  INFO [83faa4b8] Running which docker on 18.236.160.208
  INFO [712cdba0] Finished in 0.174 seconds with exit status 0 (successful).
  INFO [b77e3e64] Finished in 0.179 seconds with exit status 0 (successful).
  Deploy lock was not released
  Finished all in 2.2 seconds
  Deploy lock was not released
  ERROR (Errno::ECONNRESET): Connection reset by peer
```

My work around this for now is to only work with 10 servers at a time. It's a little slow but that does work.

**Comment by northeastprince** [comment]
I assume this something with your connection/network as 37signals deploys to a bunch of servers

**Comment by dhh** [comment]
You can use the pre-connect hook sample to warm DNS: https://github.com/mrsked/mrsk/blob/f0301d20071c3d16259203468e4cde91cd089768/lib/mrsk/cli/templates/sample_hooks/pre-connect.sample.

Will work on putting this directly into mrsk though.

**Comment by djmb** [comment]
@russ - we've had some issues when deploying to large numbers of hosts that were caused by SSHKit trying to start lots of  SSH connections.

https://github.com/mrsked/mrsk/pull/399 fixed those for us by adding a concurrency limit on connection starts. It defaults to 30, but you can try lower values as well.

Would be interested to know if that also fixes this issue for you!
