### ISSUE TITLE
Allow using a single env template for multiple outputs

### ISSUE THREAD

**Issue by Zeko369** [basecamp/kamal#351]
We're doing a multi-tenant SaaS where we deploy multiple environments per customer so we'd like to have a `.env.[stage|production].erb` that's used to generate all tenant envs i.e. `.env.stage-microsoft` or `.env.production-google` (instead of having 2 * number of tenants .env templates)

Something along the lines of `bin/mrsk envify -d google -t .env.stage.erb` -> `.env.stage-google`

Also to make this more configurable we'd use `<%= ENV['MRSK_DESTINATION'] %>` inside of the template to differentiate between destinations

**Comment by djmb** [comment]
We've removed `kamal envify` in Kamal 2
