### ISSUE TITLE
Add delay before starting healtcheck

### ISSUE THREAD

**Issue by Zeko369** [basecamp/kamal#361]
In cases the app starts slower it might timeout while waiting for healthchecks to succeeded, our app for example starts up in 6th or 7th attempt (of the default 7) and while we can increase that to 8/9 it seams like a smarter thing would be to just "delay 10s" and then start the 1/2/3/4 sequence

This might make it faster since if the app starts in i.e. 20s and doesn't hit the 6th (21s) you need to wait for the next one which is 28s, while if we just add a 18s delay at the start it's gonna hit it faster (since the timeouts at the point will be 1/2/3s)

**Comment by dorianmariecom** [comment]
from @dhh on the pull request:

> Not loving this. Having two independent dials to turn for this is imo too much.

So I think this should be closed no?

**Comment by JohnYangSam** [comment]
Regarding this question, what is the best practice for configuring the kamal proxy healthchecks for containers that take a long time to fully start?

e.g. I have a container running Django migrations and need to re-run it several times to incrementally run the migrations with kamal failing each time until it finally makes it through on the migrations to pass the healthcheck.

From the documentation, is it correct that:
`interval:` is how often the server is pinged (e.g. `interval: 3` is every 3 seconds)
`timeout:` Is the total time kamal waits for the container to be healthy? e.g. the `5-second timeout for each request` for each request is different than this configured `timeout:`?

![Screenshot 2024-12-09 at 1 06 01 AM](https://github.com/user-attachments/assets/36148a2f-b8c2-42ef-a08d-40913228c723)
