### ISSUE TITLE
Execution of interactive commands are limited to "web" role

### ISSUE THREAD

**Issue by nlsrchtr** [basecamp/kamal#381]
Thanks for building this nice tooling around plain docker deployments. It's a huge help for me!

I was trying to jump into a background worker with an interactive shell like:

`mrsk app exec -i 'bash' -d staging --reuse -r job -i`

With the `-r`option it is respecting the switch of host, but on that host, it will search for a container including the "web" role. Looking into the source code, I think fixing the role to "web" in [here](https://github.com/mrsked/mrsk/blob/9a501867b438761239b32c9a8ae7c750aa4d12c6/lib/mrsk/cli/app.rb#L93C32-L93C32) causes this behaviour.

I think using just the input from the `-r` option would be the best bet here. I can provide a MR, if I get some more guidance on the preferred implementation.

**Comment by dhh** [comment]
Please do explore a fix 👍

**Comment by djmb** [comment]
This was fixed at some point.
