### ISSUE TITLE
`mrsk setup` gives SSH-2.0-Ruby/Net::SSH_7.1.0: No such file or directory

### ISSUE THREAD

**Issue by durierem** [basecamp/kamal#390]
Running `mrsk setup` gives:

```
Acquiring the deploy lock...
Pseudo-terminal will not be allocated because stdin is not a terminal.
-bash: line 1: SSH-2.0-Ruby/Net::SSH_7.1.0: No such file or directory
```

I'm running with the `proxy_command` config as follows:

```
ssh:
  proxy_command: ssh -i ~/somekey.pem user@host
```

- Debian 11
- Ruby 3.1.2
- mrsk 0.14.0

**Comment by fahu** [comment]
The proxy_command is typically used when you need to connect through a proxy or intermediary host before accessing the destination. Are you using proxy_command solely to specify a different SSH key, or do you need it to connect through a specific proxy host?

If your goal is just to specify a custom SSH key, you don't need to (and actually should not) use `proxy_command` for that.
Instead, you can load the desired SSH key into your SSH agent using the following command:
```bash
ssh-add ~/somekey.pem
```

By doing this, the key will be available for SSH sessions without having to specify it directly in the command line.
