### ISSUE TITLE
Builder is failing when using just local builder

### ISSUE THREAD

**Issue by cleanbit** [basecamp/kamal#407]
mrsk always failing if builder has just one local architecture. The issue was introduced with `v0.14.0`, downgrading to `v0.13.2` helps.

Identical [ticket](https://github.com/mrsked/mrsk/issues/377) was opened and closed instantly for some reason :)

I'm running M1 and cross-compiling to amd64

Error:

`ERROR (ArgumentError): You must specify both local and remote builder config for remote multiarch builds`

`builder` part of the config.
```
builder:
  local:
    arch: amd64
```

**Comment by scart88** [comment]
Hey @cleanbit, I switched to remote option as it was much faster to build the image. 
In addition to that the server network speed is up to 1gb and was much faster to upload to the registry.

**Comment by djmb** [comment]
I think this regression was introduced in https://github.com/mrsked/mrsk/pull/337 - cc @igor-alexandrov.

**Comment by igor-alexandrov** [comment]
Yes, it is my fault. Will prepare a fix ASAP.
