### ISSUE TITLE
`mrsk deploy` gives me ERROR (NoMethodError): undefined method `remove' for "Mrsk::Commands::Builder::Multiarch":String

### ISSUE THREAD

**Issue by jasonfb** [basecamp/kamal#421]
% mrsk deploy      
```
Acquiring the deploy lock...
Log into image registry...
  INFO [91e5d11c] Running docker login -u [REDACTED] -p [REDACTED] as jason@localhost
  INFO [91e5d11c] Finished in 0.720 seconds with exit status 0 (successful).
  INFO [036062d9] Running docker login -u [REDACTED] -p [REDACTED] on 54.196.71.166
  INFO [036062d9] Finished in 0.154 seconds with exit status 0 (successful).
Build and push app image...
Releasing the deploy lock...
  Finished all in 1.4 seconds
  ERROR (NoMethodError): undefined method `remove' for "Mrsk::Commands::Builder::Multiarch":String

    target.class.to_s.remove("Mrsk::Commands::Builder::").underscore.inquiry
                     ^^^^^^^
```

**Rails 7.1.0.alpha**
**MRSK 0.15.1**

for reference, I am writing this (WIP) setup guide for MRSK on EC2
https://jasonfleetwoodboldt.com/courses/rails-7-crash-course/mrsk-on-amazon-ec2

**Comment by jasonfb** [comment]
my `config/deploy.yml` file is
```
# Name of your application. Used to uniquely configure containers.
service: helios-panoptes

# Name of the container image.
image: jasonheliosdevshop/helios-panoptes

# Deploy to these servers.
servers:
  - 54.196.71.166

# Credentials for your image host.
registry:
  username:
    - DOCKER_USERNAME
  password:
    - DOCKER_PASSWORD

env:
  secret:
    - RAILS_MASTER_KEY
ssh:
  user: ubuntu

builder:
  args:
    RUBY_VERSION: "<%= Pathname.pwd.join('.ruby-version').read.strip.delete_prefix('ruby-') %>"
    BUNDLER_VERSION: "<%= Bundler::LockfileParser.new(Pathname.pwd.join('Gemfile.lock').read).bundler_version %>"
    RAILS_MASTER_KEY: "<%= ENV['RAILS_MASTER_KEY'] %>"


```

**Comment by fig** [comment]
`String#remove` is proved by `active_support/core_ext/string/filters` but it doesn't look this module is required anywhere.

**Comment by northeastprince** [comment]
Having a similar issue:

![image](https://github.com/mrsked/mrsk/assets/55164724/acbb0a56-cb55-416f-888a-acaa7edb2cda)

**Comment by garyhtou** [comment]
It looks like this recent change to Rails may be the cause of the issue

https://github.com/rails/rails/pull/48959

**Comment by jasonfb** [comment]
if rails is alpha not sure if they want Issue reports via Github. either way, are you sure it is in Rails? if so, I'll close here.

**Comment by northeastprince** [comment]
Yeah, but it seems to be an intended change so it's still on MRSK to fix the usage of it.

**Comment by fig** [comment]
Kamal was relying on Rails to load the required module. This is not a great idea. As we have seen, our dependencies may choose to drop features we are using. Much better to be explicit. It's more wordy, but does not impact performance. Ruby will only load a file once. If it is already loaded, subsequent `require` calls will simply return `nil`.

This has been a good learning opportunity.
