### ISSUE TITLE
Try running `bin/kamal` when calling global mrsk

### ISSUE THREAD

**Issue by Zeko369** [basecamp/kamal#435]
Similar to how rails defaults to trying to run `bin/rails` and then falls back to running internal commands if `bin/rails` isn't found it would be great if kamal could do that

(Our specific usecase: since we have a multitenant setup you can't run `bin/kamal` without `-d`, so we added a case that checks for that and raises an error if you didn't pass it, but if you call `kamal` (global) it's being ignored, also we prepend some args / preload some methods and would love to have them when calling both `bin/kamal` and global `kamal`)

**Comment by dhh** [comment]
You can now use https://github.com/basecamp/kamal/pull/451 for this.
