### ISSUE TITLE
Why does `kamal build` take a deploy lock?

### ISSUE THREAD

**Issue by djmb** [basecamp/kamal#455]
### Discussed in https://github.com/basecamp/kamal/discussions/446

<div type='discussions-op-text'>

<sup>Originally posted by **clintmiller** September  6, 2023</sup>
Is there a specific reason that calling `kamal build` takes the deploy lock? It seems like it should be generally safe for builds to run concurrently, regardless of the environment in which they are executed.

Surely I'm just overlooking something simple?</div>

**Comment by dhh** [comment]
Should definitely be fine to run builds concurrently and therefore no need for a lock.

**Comment by djmb** [comment]
Fixed by #755
