### ISSUE TITLE
Guide to change from mrsk

### ISSUE THREAD

**Issue by talhashoaib** [basecamp/kamal#483]
Is there any documentation or guide to change from mrsk to kamal ?

**Comment by djmb** [comment]
Hi @talhashoaib!

Specifically for the MRSK -> Kamal switch if you rename files (i.e `.hooks/mrsk`, `bin/mrsk` if you have them) and any references in code (`MRSK_PERFORMER` etc), everything should work as before.

There are some upgrade steps in v1.0.0 of Kamal that you'll need to follow as well [in the release notes](https://github.com/basecamp/kamal/releases/tag/v1.0.0).

If you want to avoid doing both at once, you could upgrade from MRSK -> Kamal v0.16.1 -> Kamal v1.0.0.
