### ISSUE TITLE
Can I store the config separate from the actual app I'm deploying?

### ISSUE THREAD

**Issue by dotnofoolin** [basecamp/kamal#484]
Scenario: My devops team wants to manage all 5 Rails apps with Kamal, but they don't want to commit/PR in each of the 5 Rails apps to setup/maintain Kamal (for example, they want to spin up a new server to scale a load sometime in the future, but they don't want to interrupt the Rails app release cycle or force a hotfix). They want to create one repo in our org that houses all the Kamal configs for all our Rails apps. Then they want to build a minimal server that sits next to our prod servers just for running Kamal deploys from, which will pull down the master Kamal config repo. Can the Kamal config point to a git repo (say on Github or Bitbucket) for my Rails app?

One plus I see in this is I can limit who has access to the "deploy" server and we still keep app code separate from devops code.

Possible? Dumb idea?

**Comment by Halhamd813** [comment]
أرسل حامد مصلح إليك رسالة إلكترونية في وضع الحفاظ على السرّية في Gmail:

[image: شعار Gmail]Re: [basecamp/kamal] Can I store the config separate from the actual app I'm deploying? (Issue #484) <https://confidential-mail.google.com/msg/AJ05Yhfiw185DWxhAVUe5oGTfkt9o0TqFl06_3y4wWGamTPwA9bfRhmFfoRZf0Y0A5Y4vt3L-feXKs1SGy4vn4iNFcVrOORt3csz59kUcBV9VGG_ar2WbQzWo2nzhuzhdDJvux4GStyQHf8Xphqol1MqzWUuidCH8i5-NNyeXKGXrtyIHf_fQa_unSE0BGmUdUdo-NHGz3gl>

تم إرسال هذه الرسالة يوم 20‏/09‏/2023 الساعة 3:45:30 م غرينتش-7
يمكنك فتحه بالنقر على الرابط أدناه. ولا يعمل هذا الرابط إلا مع ***@***.***

عرض الرسالة الإلكترونية <https://confidential-mail.google.com/msg/AJ05Yhfiw185DWxhAVUe5oGTfkt9o0TqFl06_3y4wWGamTPwA9bfRhmFfoRZf0Y0A5Y4vt3L-feXKs1SGy4vn4iNFcVrOORt3csz59kUcBV9VGG_ar2WbQzWo2nzhuzhdDJvux4GStyQHf8Xphqol1MqzWUuidCH8i5-NNyeXKGXrtyIHf_fQa_unSE0BGmUdUdo-NHGz3gl>

يمنحك "الوضع السري في Gmail" مزيدًا من التحكُّم في الرسائل التي تُرسِلها. ربما اختار المُرسِل تحديد وقت انتهاء الصلاحية أو إيقاف الطباعة أو إعادة توجيه رسالة أو تتبّع الوصول إلى هذه الرسالة. مزيد من المعلومات <https://support.google.com/mail/answer/7674059>
Gmail: خدمة بريد إلكتروني مُقدَّمة من Google
يخضع الاستخدام لـ سياسة خصوصية Google <https://myaccount.google.com/privacypolicy?hl=ar>
Google LLC, 1600 Amphitheatre Parkway, Mountain View, CA 94043, USA
لقد استلمت هذه الرسالة لأن أحدهم أرسل إليك رسالة إلكترونية في وضع الحفاظ على السرّية في Gmail.
[image: شعار Google]

**Comment by djmb** [comment]
Hi @dotnofoolin,

I have not tried this, so I'm not 100% sure it would work, but I think it should.

First add a hook in `.hook/kamal/pre-build` that checks out the version of the app you want to deploy somewhere.

Specify the dockerfile from that checkout in your config.
```
builder:
  dockerfile: /path/to/checkout/Dockerfile
```

Do let me know if this works!
