### ISSUE TITLE
Skip building and pushing images

### ISSUE THREAD

**Issue by dviana19** [basecamp/kamal#486]
Some teams/people are already using other ways for building and pushing images to their registry(such as GitHub actions, circleCI, and so on).

Kamal could offer an option to skip the build/push for those who don't need that step, only pull.

**Comment by adrienpoly** [comment]
isn't is `--skip-push` that you are looking for?

<img width="748" alt="CleanShot 2023-09-21 at 13 02 52@2x" src="https://github.com/basecamp/kamal/assets/7847244/d647e659-7db5-4ef6-b87e-fbe3a9fa9592">

**Comment by dviana19** [comment]
Hey @adrienpoly, thank you! That's exactly what I was looking for but didn't find in the documentation.
