### ISSUE TITLE
Is it possible to host multiple site per machine?

### ISSUE THREAD

**Issue by vldmr-k** [basecamp/kamal#494]
Hi everyone.
Traefik can manage multiple docker container per machine.
But, how it manage via kamal.

For exampel I have two webapps, `site-a.com` and `site-b.com`, all of them has own `config/deplog.yml` file with `treafik:` sections, and I want to deploy theese apps to `node1`

When I deployed `site-a.com`. Kamal configurated and deployed traefik. 
After that I want to deploy `site-b.com`. 

**And, what kamal do with configurated treafik from `deploy.yml` of `site-a.com`?**

**Comment by meglio** [comment]
The "configuration" documentation shows examples about how to do it:
https://kamal-deploy.org/docs/configuration

Search for "multiple" in the page.

<img width="1182" alt="image" src="https://github.com/basecamp/kamal/assets/282177/9e0f4ba8-531e-4d16-ae78-7fbe79be0af5">

**Comment by matoakley** [comment]
For anyone reaching this page looking for the answer, the page linked by @meglio above has moved to https://kamal-deploy.org/docs/configuration/container-labels/
