### ISSUE TITLE
Permission denied for docker with file .kamal/env/traefik/traefik.env

### ISSUE THREAD

**Issue by jvillarejo** [basecamp/kamal#504]
I've followed the installation guide, I have everything configured like the example.

Also `ssh` user on the server is `root`.
   
When I run my first `kamal setup` it outputs:

```
  INFO [be986ec9] Running docker container start traefik || docker run --name traefik --detach --restart unless-stopped --publish 80:80 --volume /var/run/docker.sock:/var/run/docker.sock --env-file .kamal/env/traefik/traefik.env --log-opt max-size="10m" traefik:v2.9 --providers.docker --log.level="DEBUG" on HOST
  Finished all in 26.5 seconds
Releasing the deploy lock...
  Finished all in 34.8 seconds
  ERROR (SSHKit::Command::Failed): Exception while executing on host HOST: docker exit status: 125
docker stdout: Nothing written
docker stderr: Error response from daemon: No such container: traefik
Error: failed to start containers: traefik
docker: open .kamal/env/traefik/traefik.env: permission denied.
 ```

I've replaced my host ip with HOST.

The permissions for the file `traefik.env` in the server are:

```
-rw------- 1 root root 1 Sep 28 14:02 env/traefik/traefik.env
```

I've tried `usermod -aG docker root` but the group `docker` doesn't exists.

Also I've tried to `chmod 755` to change the permissions to file, but it stills output the same error.

**Comment by SimonBirrell** [comment]
I have the same permissions on traefik.env
I have the same error messages.

My traefik.env file is empty - I’m not sure if that matters. Did you solve the problem jvillarejo?

**Comment by jvillarejo** [comment]
I launched another VPS with latest Ubuntu version (on Digital Ocean) and it worked correctly. 

So I assumed there must be something with old VPS (Ubuntu 20.04.6 LTS (GNU/Linux 5.4.0-163-generic x86_64))

**Comment by SimonBirrell** [comment]
I'm on Ubuntu 22.04.

I can shell into the target PC as root, and read and write .kamal/env/traefik/traefik.env without a problem.

I've tried deleting the file and it gets recreated each time (always as blank). The error persists.

My deploy.yml file looks like this:

```
# Name of your application. Used to uniquely configure containers.
service: luxfleet

# Name of the container image.
image: simonbirrell/luxfleet

# Deploy to these servers.
servers:
  web:
    - 192.168.0.27

# Credentials for your image host.
registry:
  # Specify the registry server, if you're not using Docker Hub
  # server: registry.digitalocean.com / ghcr.io / ...
  username: <REDACTED>

  # Always use an access token rather than real password when possible.
  password:
    - KAMAL_REGISTRY_PASSWORD

# Inject ENV variables into containers (secrets come from .env).
# Remember to run `kamal env push` after making changes!
env:
  clear:
    DB_HOST: 192.168.0.27
  secret:
    - RAILS_MASTER_KEY
```

The application is Rails, generated with 7.1beta3 (subsequently upgraded to 7.1). I'm just using Kamal to upload the web part, as I already have PostgresQL installed on the server.

The errors are:

```
  INFO [00369250] Running docker container start traefik || docker run --name traefik --detach --restart unless-stopped --publish 80:80 --volume /var/run/docker.sock:/var/run/docker.sock --env-file .kamal/env/traefik/traefik.env --log-opt max-size="10m" traefik:v2.9 --providers.docker --log.level="DEBUG" on 192.168.0.27
  Finished all in 15.8 seconds
Releasing the deploy lock...
  Finished all in 17.1 seconds
  ERROR (SSHKit::Command::Failed): Exception while executing on host 192.168.0.27: docker exit status: 125
docker stdout: Nothing written
docker stderr: Error response from daemon: No such container: traefik
Error: failed to start containers: traefik
docker: open .kamal/env/traefik/traefik.env: permission denied.
See 'docker run --help'.
```

**Comment by SimonBirrell** [comment]
Incidentally, `kamal remove`also fails similarly:

```
kamal remove
  INFO [8652e1a9] Running /usr/bin/env mkdir -p .kamal on 192.168.0.27
  INFO [8652e1a9] Finished in 0.310 seconds with exit status 0 (successful).
Acquiring the deploy lock...
This will remove all containers and images. Are you sure? [y, N] (N) y
  INFO [d1c39b9a] Running docker container stop traefik on 192.168.0.27
Releasing the deploy lock...
  ERROR (SSHKit::Command::Failed): Exception while executing on host 192.168.0.27: docker exit status: 1
docker stdout: Nothing written
docker stderr: Error response from daemon: No such container: traefik
```

**Comment by SimonBirrell** [comment]
Found the problem, for anyone else who encounters it.

When I ran `kamal setup` originally, it didn't manage to install Docker on the target PC. I installed it myself using `snap`. According to this post [https://stackoverflow.com/questions/61876116/how-to-remove-a-snap-application-docker-completely](https://stackoverflow.com/questions/61876116/how-to-remove-a-snap-application-docker-completely) 
snap installs Docker with restricted permissions:

So I uninstalled Docker with Snap and then manually used the following to install Docker:

```
sudo apt-get remove docker docker-engine docker.io
sudo apt-get update
sudo apt install docker.io
```
 
The subsequent call to `kamal setup` worked just fine!

**Comment by jvillarejo** [comment]
Cool @SimonBirrell !

Glad you found it. Now I've realized I had also docket installed with snap.

Should we implement a better error message that docker was already installed?

Is there a way to check if docker was installed with the right permissions or through snap?

So we can display a better error message during the setup command.

**Comment by SimonBirrell** [comment]
One obvious way would be to check permissions when Kamal checks for installation of Docker, perhaps through reading a dummy env file. If it fails, Kamal could ask the user to check the Docker installation.

On the other hand, the existing message is accurate (`docker: open .kamal/env/traefik/traefik.env: permission denied.`). What wasn't clear was the cause! It's possible that with existence of this issue, and the magic of Google, there won't be a need for anything else.
