### ISSUE TITLE
Shell expansion on `kamal env push`?

### ISSUE THREAD

**Issue by northeastprince** [basecamp/kamal#505]
#438 made it possible not to expose production secrets to all deployers, which is great, but it also took away shell expansion of environment variables on the servers you're deploying to. I was using that to be able to get the hostname from inside the container (for observability, etc.). Would people be open to changing the behavior of `kamal env push` so that it evaluates the variables as it's being uploaded on each server?

**Comment by djmb** [comment]
Support for this was re-added with https://github.com/basecamp/kamal/pull/732. I've updated the docs here - https://github.com/basecamp/kamal-site/pull/69
