### ISSUE TITLE
`envify` does not correctly change/update the value of a changed secret environment variable

### ISSUE THREAD

**Issue by Antvirf** [basecamp/kamal#512]
Not sure what's going on here, seems like the local part of `envify` is working exactly as expected, but the transfer to the target machine seems to somehow be cached in a way I do not understand and haven't found a reference to in the docs.

## Steps to replicate the issue

1. Add a new line to `.env.erb`, `ASD="asd"`
2. Run `kamal envify`. Now my local `.env` file has the line `ASD="asd"`
3. On the target machine, run `cat .kamal/env/roles/myapp.env | grep ASD` - nothing shows up, as its not in config yet
4. Add the variable as a secret to `deploy.yml`:
  ```yaml
  env:
    secret:
      - ASD
  ```
5. Run `kamal envify`
6. On the target machine, run `cat .kamal/env/roles/myapp.env | grep ASD` - now I get a value `ASD=asd` as expected
7. Change the value in `.env.erb` to `ASD="def"`
8. Run `kamal envify`. Now my **local** `.env` file has the line `ASD="def"` as expected
9. On the target machine, run `cat .kamal/env/roles/myapp.env | grep ASD` - **this still gives `ASD=asd`**

## Other notes/info

- I have tried clearing `.kamal/env/` directory entirely, this does not work either. The old value for the secret is still pushed to the target machine.
- My target machine is an AWS EC2 instance

**Comment by frenkel** [comment]
Did you forget to run `kamal env push`?

**Comment by djmb** [comment]
Hi @Antvirf, thanks you for this report. I had seen this issue but not got to the bottom of it so this report was very useful!

Should be resolved by https://github.com/basecamp/kamal/pull/557
