### ISSUE TITLE
Docker service not started on host

### ISSUE THREAD

**Issue by rejacobson** [basecamp/kamal#521]
Running `kamal setup` with brand new hosts exits with this error:

```
ERROR (SSHKit::Command::Failed): Exception while executing on host 23.34.45.56: docker exit status: 125
docker stdout: Nothing written
docker stderr: docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.
See 'docker run --help'.
```

I'm using a Fedora 38 host on Hetzner.

Docker Installation succeeds, but is not started.

I have to ssh in to the new host and run, `systemctl start docker`, then I can run `kamal setup` successfully.

**Comment by djmb** [comment]
Closing this as stale, we can re-open later if we have more info
