### ISSUE TITLE
Ensure cleanup file system before `docker build`. Opinion needed.

### ISSUE THREAD

**Issue by igor-alexandrov** [basecamp/kamal#524]
I opened PR that adds `vendor/bundle` to `.dockerignore` file template in Rails repo: https://github.com/rails/rails/pull/48540.

However, @byroot correctly mentioned that `vendor/bundle` can be used by some applications, and maybe it is not a good idea to add it to `.dockerignore` and `.gitignore`. Instead, he proposed that Kamal ensure a clean file system before `docker build`.

I want to hear your opinion on this case and find the best solution.

**Comment by byroot** [comment]
To clarify, I think beyond this specific `vendor/bundle` issue that is happening to you, building from a directory that may contain local modifications that weren't committed is risky, as you may accidentally include things you didn't intent do.

It may make sense for kamal to build from a temporary directory created with `git archive` or similar.

I'm really unfamiliar with kamal though so not too sure.
