### ISSUE TITLE
starting with just `kamal deploy` fails (no `kamal setup`)

### ISSUE THREAD

**Issue by mcgaw** [basecamp/kamal#538]
I've manually installed the pre-requisites on the target machine. An initial deploy fails due to a missing `.env` file it seems:

```
  INFO [392febf3] Running docker container start traefik || docker run --name traefik --detach --restart unless-stopped --publish 80:80 --volume /var/run/docker.sock:/var/run/docker.sock --env-file .kamal/env/traefik/traefik.env --log-opt max-size="10m" traefik:v2.9 --providers.docker --log.level="DEBUG" on vagrant-box
Releasing the deploy lock...
  Finished all in 16.9 seconds
  ERROR (SSHKit::Command::Failed): Exception while executing on host vagrant-box: docker exit status: 125
docker stdout: Nothing written
docker stderr: Error response from daemon: No such container: traefik
Error: failed to start containers: traefik
docker: open .kamal/env/traefik/traefik.env: no such file or directory.
See 'docker run --help'.
```
It's remedied by executing the `setup` command first (which is in itself oddly named and I wouldn't expect it to deploy anything). However the docs state that it should not be necessary to run this step. Personally I'm not convinced the server setup should be conflated with the tool itself, but that's a digression.

**Comment by Matic** [comment]
I agree, lost quite a bit of time before I figured out that if I add additional server roles or accessories I need to run `setup` again.

**Comment by Matic** [comment]
`kamal env push` creates the env directories and pushes the distilled .env files for each container as far as I understand. However when I added a new accessory, a simple `deploy` didn't work. Maybe it was related to something else. When I nuked everything and retried with `setup` then everything started working.

**Comment by mpolakis** [comment]
Thank you

**Comment by dbackeus** [comment]
I'm ran into this error even though the only command I had been running was `kamal setup` (as advertised in https://kamal-deploy.org/docs/installation/).

I had to explicitly run `kamal env push` to pass this step.

**Comment by djmb** [comment]
Hmm `kamal envify` sometimes calls `kamal env push`, but not always! That's my mistake. I'll revert that change.

**Comment by djmb** [comment]
Reverted here - https://github.com/basecamp/kamal/pull/845
