### ISSUE TITLE
Command --skip-push fails when only the deploy.yml is changed.

### ISSUE THREAD

**Issue by jefvlamings** [basecamp/kamal#545]
When you make a change in deploy.yml you can't use the flag `--skip-push` or `-P` to redeploy without building/pushing.
It looks like a new manifest (or image id?) is generated when any of the files in the directory are changed. 

### Steps to reproduce

1. deploy with `kamal deploy`
2. change `deploy.yml`
3. redeploy with `kamal redeploy --skip-push`

### Context
When setting up a new project you'll find yourself fiddling with the configuration a lot. Today I was trying to figure out how to do a redirect with traefik. I had to try a couple of different settings and had to do a full redeploy each time. It would be nice to be able to use `--skip-push` and speed up the trail-and-error process.

### Error message
```
kamal redeploy --skip-push
  INFO [357c7314] Running /usr/bin/env mkdir -p .kamal on ***
  INFO [357c7314] Finished in 0.833 seconds with exit status 0 (successful).
Acquiring the deploy lock...
Pull app image...
  INFO [0283dd09] Running docker image rm --force registry/app:18fd23b39f369ffd598e5b20896c2abdf3ab3147_uncommitted_4b09fbfd84e81676 on ***
  INFO [0283dd09] Finished in 0.382 seconds with exit status 0 (successful).
  INFO [86d7da4d] Running docker pull registry/app:18fd23b39f369ffd598e5b20896c2abdf3ab3147_uncommitted_4b09fbfd84e81676 on ***
Releasing the deploy lock...
  Finished all in 3.4 seconds
  ERROR (SSHKit::Command::Failed): Exception while executing on host ***: docker exit status: 1
docker stdout: Nothing written
docker stderr: Error response from daemon: manifest for registry/app:18fd23b39f369ffd598e5b20896c2abdf3ab3147_uncommitted_4b09fbfd84e81676 not found: manifest unknown: manifest unknown
```

Reference: #497

**Comment by GeNiuS69** [comment]
@jefvlamings try use `--version=latest` or any other tag that you have
