### ISSUE TITLE
Setting web server ip as docker web container ip

### ISSUE THREAD

**Issue by RailsCod3rFuture** [basecamp/kamal#548]
What would be the best method for trusting docker container ip addresses within digitalocean. I know --network="host" doesn't work with swarm mode.....pretty sure that might be using for deploying to multiple web containers. But I want the database to be connected to only my web servers and not exposed to the internet.

**Comment by eminkel** [comment]
If your database is being commanded by Kamal via an accessory here is a way:

`
servers:
  web:
    hosts:
      - IP A
      - IP B
    options:
      # this is allowing the communication on the internal docker network
      "add-host": host.docker.internal:host-gateway
accessories:
  db:
    image: postgres:15
    roles:
      - web
    # this is explicitly setting 5432 port to be available over the docker internal network
    port: "172.17.0.1:5432:5432"
    directories:
      - data:/var/lib/postgresql/data
`

Since your app containers will run on the docker internal network, now your database lives in the same spot but as an accessory.

**Comment by RailsCod3rFuture** [comment]
I have this set `"add-host": host.docker.internal:host-gateway` but I'm using a managed database. I need the ip to match the actual server that its hosted on...in order to whitelist it.

**Comment by RailsCod3rFuture** [comment]
If anyone comes up with a way to easily implement a structure for making docker ips easily trusted...let me know.
