### ISSUE TITLE
Custom SSH key

### ISSUE THREAD

**Issue by Matic** [basecamp/kamal#555]
I'm new to kamal and I can't find a way to specify the private ssh key to use for ssh. I can only modify the user or setup a proxy. Did I miss something? Otherwise I think this would make a great option.

**Comment by fabiendv** [comment]
You can add a config file into the .ssh folder and specify your key.

Here is an example:
````
Host MY.HOST.IP
  User ubuntu
  IdentityFile ~/.ssh/your-key.pem
````

**Comment by serv** [comment]
@fabiendv 
I have this setup for my `~/.ssh/config` file but `kamal setup` command doesn't seem to respect the ssh config setting.

When I run `kamal setup`

```
$ kamal setup
  INFO [9b0f2031] Running /usr/bin/env mkdir -p .kamal on x.x.x.x
  INFO [98f565a2] Running /usr/bin/env mkdir -p .kamal on y.y.y.y
  Finished all in 0.8 seconds
  ERROR (Net::SSH::AuthenticationFailed): Exception while executing on host x.x.x.x: Authentication failed for user root@x.x.x.x
```

`~/.ssh/config` file

```
Host x.x.x.x
  IdentityFile ./kamal-rails-pg-tutorial-app-1_key.pem
  User azureuser
Host y.y.y.y
  IdentityFile ./kamal-rails-pg-tutorial-app-2_key.pem
  User azureuser
```

**Comment by serv** [comment]
Solved the problem.

I needed to update the permission of the pem keys.

`chmod 400 kamal-rails-pg-tutorial-app-1_key.pem`

And add the key to ssh-add

`ssh-add kamal-rails-pg-tutorial-app-1_key.pem`
