### ISSUE TITLE
Health check not working for Elixir/Phoenix app?

### ISSUE THREAD

**Issue by mitkins** [basecamp/kamal#574]
Hi! I'm testing Kamal with a Phoenix web app (from a Windows PC). When I run `kamal setup` as far as I can tell, the app is successfully building the Dockerfile.

I setup a route in my app so that `https://localhost:4000/up` will return a 200

Here's my `deploy.yml` file:

```
# Name of your application. Used to uniquely configure containers.
service: syneng-goodbye

# Name of the container image.
image: mitkins/syneng-goodbye

# Deploy to these servers.
servers:
  - localhost:2022

# Credentials for your image host.
registry:
  username: mitkins

  password:
    - KAMAL_REGISTRY_PASSWORD

ssh:
  user: ham

# Configure a custom healthcheck (default is /up on port 3000)
healthcheck:
  path: /up
  port: 4000
```

When it comes to the part where it pre-checks the healthcheck. It does not pass:

```
  INFO [39ee30f4] Running docker login -u [REDACTED] -p [REDACTED] on localhost
  INFO [39ee30f4] Finished in 3.254 seconds with exit status 0 (successful).
  INFO [30f8f55d] Running docker container start traefik || docker run --name traefik --detach --restart unless-stopped --publish 80:80 --volume /var/run/docker.sock:/var/run/docker.sock --env-file .kamal/env/traefik/traefik.env --log-opt max-size="10m" traefik:v2.9 --providers.docker --log.level="DEBUG" on localhost
  INFO [30f8f55d] Finished in 0.139 seconds with exit status 0 (successful).
Ensure app can pass healthcheck...
  INFO [4f7b6fd8] Running docker run --detach --name healthcheck-syneng-goodbye-c3d5dc32b3f94c212be3ecba4bf920c4be177512 --publish 3999:4000 --label service=healthcheck-syneng-goodbye -e KAMAL_CONTAINER_NAME="healthcheck-syneng-goodbye" --env-file .kamal/env/roles/syneng-goodbye-web.env --health-cmd "curl -f http://localhost:4000/up || exit 1" --health-interval "1s" mitkins/syneng-goodbye:c3d5dc32b3f94c212be3ecba4bf920c4be177512 on localhost
  INFO [5a5ee870] Running docker container ls --all --filter name=^healthcheck-syneng-goodbye-c3d5dc32b3f94c212be3ecba4bf920c4be177512$ --quiet | xargs docker stop on localhost
  INFO [5a5ee870] Finished in 0.186 seconds with exit status 123 (failed).
  INFO [c773c103] Running docker container ls --all --filter name=^healthcheck-syneng-goodbye-c3d5dc32b3f94c212be3ecba4bf920c4be177512$ --quiet | xargs docker container rm on localhost
  INFO [c773c103] Finished in 0.171 seconds with exit status 123 (failed).
Releasing the deploy lock...
  Finished all in 36.1 seconds
  ERROR (SSHKit::Command::Failed): Exception while executing on host localhost: docker exit status: 125
docker stdout: Nothing written
docker stderr: docker: open .kamal/env/roles/syneng-goodbye-web.env: no such file or directory.
See 'docker run --help'.
```

I assume that the missing `syneng-goodbye-web.env` file is the cause of the problem. However, I'm not sure what I should do at this stage to address the problem. Does anybody have any suggestions?

**Comment by mitkins** [comment]
Just in case, here's the Dockerfile. It was generated using `mix phx.gen.release --docker`. The only thing I did was add `ENV ERL_FLAGS="+JPperf true"`:

```Dockerfile
# Find eligible builder and runner images on Docker Hub. We use Ubuntu/Debian
# instead of Alpine to avoid DNS resolution issues in production.
#
# https://hub.docker.com/r/hexpm/elixir/tags?page=1&name=ubuntu
# https://hub.docker.com/_/ubuntu?tab=tags
#
# This file is based on these images:
#
#   - https://hub.docker.com/r/hexpm/elixir/tags - for the build image
#   - https://hub.docker.com/_/debian?tab=tags&page=1&name=bullseye-20231009-slim - for the release image
#   - https://pkgs.org/ - resource for finding needed packages
#   - Ex: hexpm/elixir:1.15.7-erlang-26.1.2-debian-bullseye-20231009-slim
#
ARG ELIXIR_VERSION=1.15.7
ARG OTP_VERSION=26.1.2
ARG DEBIAN_VERSION=bullseye-20231009-slim

ARG BUILDER_IMAGE="hexpm/elixir:${ELIXIR_VERSION}-erlang-${OTP_VERSION}-debian-${DEBIAN_VERSION}"
ARG RUNNER_IMAGE="debian:${DEBIAN_VERSION}"

FROM ${BUILDER_IMAGE} as builder

# install build dependencies
RUN apt-get update -y && apt-get install -y build-essential git \
    && apt-get clean && rm -f /var/lib/apt/lists/*_*

# prepare build dir
WORKDIR /app

# install hex + rebar
RUN mix local.hex --force && \
    mix local.rebar --force

# set build ENV
ENV MIX_ENV="prod"
ENV ERL_FLAGS="+JPperf true"

# install mix dependencies
COPY mix.exs mix.lock ./
RUN mix deps.get --only $MIX_ENV
RUN mkdir config

# copy compile-time config files before we compile dependencies
# to ensure any relevant config change will trigger the dependencies
# to be re-compiled.
COPY config/config.exs config/${MIX_ENV}.exs config/
RUN mix deps.compile

COPY priv priv

COPY lib lib

COPY assets assets

# compile assets
RUN mix assets.deploy

# Compile the release
RUN mix compile

# Changes to config/runtime.exs don't require recompiling the code
COPY config/runtime.exs config/

COPY rel rel
RUN mix release

# start a new build stage so that the final image will only contain
# the compiled release and other runtime necessities
FROM ${RUNNER_IMAGE}

RUN apt-get update -y && \
  apt-get install -y libstdc++6 openssl libncurses5 locales ca-certificates \
  && apt-get clean && rm -f /var/lib/apt/lists/*_*

# Set the locale
RUN sed -i '/en_US.UTF-8/s/^# //g' /etc/locale.gen && locale-gen

ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8

WORKDIR "/app"
RUN chown nobody /app

# set runner ENV
ENV MIX_ENV="prod"
ENV ERL_FLAGS="+JPperf true"

# Only copy the final release from the build stage
COPY --from=builder --chown=nobody:root /app/_build/${MIX_ENV}/rel/goodbye ./

USER nobody

# If using an environment that doesn't automatically reap zombie processes, it is
# advised to add an init process such as tini via `apt-get install`
# above and adding an entrypoint. See https://github.com/krallin/tini for details
# ENTRYPOINT ["/tini", "--"]

CMD ["/app/bin/server"]
```

**Comment by intrip** [comment]
> I assume that the missing syneng-goodbye-web.env file is the cause of the problem. However, I'm not sure what I should do at this stage to address the problem. Does anybody have any suggestions?

Have you tried running "kamal envify" before calling the setup?

**Comment by mitkins** [comment]
I don't have an `env.erb` so I get the following error:

```
ERROR (Errno::ENOENT): No such file or directory @ rb_sysopen - .env.erb
```

But I do have an existing `.env` file:

```
KAMAL_REGISTRY_PASSWORD=[REDACTED]
RAILS_MASTER_KEY=another-env
```

**Comment by mitkins** [comment]
Also, since I created this issue I found out that I could run `kamal setup` successfully with an Azure VM. The main difference is that I'm pushing to Ubuntu on the Windows Subsystem for Linux (Ubuntu). So maybe that's just problematic

I'm going to install a VM via Virtual Box and see if that works...

**Comment by mitkins** [comment]
Just confirming that deploying to a VirtualBox VM worked as expected. So there must be an issue with WSL

**Comment by mitkins** [comment]
So this happened to me when I pushed to an Azure VM. Running the following command fixed it (as you might expect):

`kamal env push -d azure`

This created the `.kamal/env/roles` directory and the `syneng-goodbye-web.env` file. It also pushes the Traefik directory and file. My Azure deploy is running successfully.

However, when I run the command against the WSL, it only pushes Traefik (i.e. it does not create the `roles` directory and associated file).

I tried creating the `syneng-goodbye-web.env` file manually and the health check works. Doing so has allowed the deploy to complete. Only now I have a different problem - when I access the server, I get the following message:

> 404 page not found

Probably another quirk to do with WSL and the deployment process. I'm not sure that I'll get this working with WSL. But I thought I'd leave this info here in case anyone goes down the same path.

**Comment by joerichsen** [comment]
I have successfully deployed several Elixir apps using kamal :-)

The last part of my Dockerfile looks like this

```
USER nobody

EXPOSE 3000

CMD ["/app/bin/server"]
```

(I added the ```EXPOSE 3000``` part)

Furthermore, I have the following lines in my ```config/deploy.production.yml``` file:
```
env:
  clear:
    PORT: 3000
```

to make Phoenix use port 3000 instead of the default port 4000.

**Comment by mitkins** [comment]
Cool. Thanks for this. The health checks were passing (because you can specify the port) so deployment was working for a non WSL target (although the deployment worked, I was yet to make the web app accessible).

I did eventually realise that I needed to do what you suggest (in particular the `env->clear->port` part). The `deploy.yml` file looks a little cleaner now. I can successfully deploy to a VirtualBox VM and an Azure VM. However, the problem (mentioned above) still remains when pushing to a WSL install.

**Comment by djmb** [comment]
You can run `kamal env push` instead of `kamal envify` if you have created the local .env file yourself.
