### ISSUE TITLE
restart command?

### ISSUE THREAD

**Issue by gammons** [basecamp/kamal#584]
Hi all,

Is there a command to restart app containers?  Or would that be accomplished by just re-deploying?

Thank you!

**Comment by djmb** [comment]
Hi @gammons! You can run `kamal app boot`. It will deploy a new container with the latest deployed version and switch over to it.

If you just want to restart the existing containers, you could do `kamal app stop; kamal app start`, but that would give you a small bit of downtime.

**Comment by gammons** [comment]
perfect.  thank you!
