### ISSUE TITLE
Asks for ssh password after upgrading kamal gem

### ISSUE THREAD

**Issue by saviokmua** [basecamp/kamal#589]
After upgrading the kamal gem version from 1.0.0 to 1.2.0
when I'm trying exec `kamal deploy` - I need to pass an SSH password

I returned to 1.0.0 and all works great

---
Ubuntu 22.04
ruby 3.2.2
bash

**Comment by vladyio** [comment]
Hi @saviokmua. I'm not sure, but I think it's not related to Kamal.

Try doing this in your terminal:

```
eval "$(ssh-agent -s)"
ssh-add -K ~/.ssh/id_rsa # or whatever your key is
```

and in your local `~/.ssh/config` make sure to have:

```
Host *
    AddKeysToAgent yes
    UseKeychain yes
    IdentityFile ~/.ssh/id_rsa
```

This should resolve the issue.

**Comment by moladukes** [comment]
^ the -K flag is deprecated but essentially you need to add your ssh the your keychain.
