### ISSUE TITLE
is it possible realese branch-based deployment on stage server with subdomains?

### ISSUE THREAD

**Issue by vldmr-k** [basecamp/kamal#612]
In my company, we use branch-based deployment for development process.
For example, when developer release big feature, he create branch `<number>-task`, and push code and branch to the github.
Our CI/CD system deploy application to stage server, and generate config for nginx with subdomain. After that, application available on domain:
`<number>-task.dev.example.com`

My questions are:
1) While reading the docs I saw that I can config [treafik host](https://kamal-deploy.org/docs/configuration#using-container-labels). Can I generate host value dynamyc? E.g.: `Host('${breanch}.dev.example.com')`?
2) Can kamal run 2-3-4 different versions the same application on the server?

Thanks.

**Comment by nickhammond** [comment]
Re: #1 I don't think you'd be able to do fully dynamic branch deploys but you could configure a bunch of destinations/servers and deploy to those. 
Re: #2 yes, you can run multiple instances of the same application you'd just have another server definition, something like `web_0`, `web_1`, etc.
