### ISSUE TITLE
ERROR: failed to solve: process "/bin/sh -c SECRET_KEY_BASE_DUMMY=1 

### ISSUE THREAD

**Issue by MagePsycho** [basecamp/kamal#624]
I am just try to deploy a simple hello world application on rails
(followed article - https://www.dotenv.org/docs/frameworks/rails/kamal)

On running `kamal setup` gave the following error 
```
Dockerfile:37
--------------------
  35 |
  36 |     # Precompiling assets for production without requiring secret RAILS_MASTER_KEY
  37 | >>> RUN SECRET_KEY_BASE_DUMMY=1 ./bin/rails assets:precompile
  38 |
  39 |
--------------------
ERROR: failed to solve: process "/bin/sh -c SECRET_KEY_BASE_DUMMY=1 ./bin/rails assets:precompile" did not complete successfully: exit code: 139
```

Any idea what went wrong?

**Comment by SebSwan** [comment]
Same problem here with ruby 3.1.3

`#22 0.129 	from ./bin/rails:3:in `<main>'
#22 ERROR: process "/bin/sh -c SECRET_KEY_BASE_DUMMY=1 ./bin/rails assets:precompile" did not complete successfully: exit code: 1

#15 [linux/arm64 stage-2 1/4] RUN apt-get update -qq &&     apt-get install --no-install-recommends -y curl libvips postgresql-client &&     rm -rf /var/lib/apt/lists /var/cache/apt/archives
#15 CANCELED
------
 > [linux/amd64 build 6/6] RUN SECRET_KEY_BASE_DUMMY=1 ./bin/rails assets:precompile:
0.129 	from /usr/local/lib/ruby/3.1.0/bundler.rb:145:in `setup'
0.129 	from /usr/local/lib/ruby/3.1.0/bundler/setup.rb:20:in `block in <top (required)>'
0.129 	from /usr/local/lib/ruby/3.1.0/bundler/ui/shell.rb:136:in `with_level'
0.129 	from /usr/local/lib/ruby/3.1.0/bundler/ui/shell.rb:88:in `silence'
0.129 	from /usr/local/lib/ruby/3.1.0/bundler/setup.rb:20:in `<top (required)>'
0.129 	from <internal:/usr/local/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
0.129 	from <internal:/usr/local/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
0.129 	from /rails/config/boot.rb:3:in `<top (required)>'
0.129 	from ./bin/rails:3:in `require_relative'
0.129 	from ./bin/rails:3:in `<main>'
------
Dockerfile:37
--------------------
  35 |     
  36 |     # Precompiling assets for production without requiring secret RAILS_MASTER_KEY
  37 | >>> RUN SECRET_KEY_BASE_DUMMY=1 ./bin/rails assets:precompile
  38 |     
  39 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c SECRET_KEY_BASE_DUMMY=1 ./bin/rails assets:precompile" did not complete successfully: exit code: 1
`

**Comment by silva96** [comment]
Had the same error. Waiting for 3.3.1 to fix it

**Comment by djmb** [comment]
Closing this as it's a Ruby bug

**Comment by ronald2wing** [comment]
Any workarounds?

**Comment by danielricecodes** [comment]
This is happening with Ruby 3.3.5.

**Comment by sdecourcel** [comment]
In order to make it work, I had to comment the line which requires master key in production.rb file :
`# config.require_master_key = true`
