### ISSUE TITLE
Sprockets choose wrong manifest with asset_path option used

### ISSUE THREAD

**Issue by aishek** [basecamp/kamal#626]
When using the `asset_path` option, Kamal copies all files from the assets folder to the brand-new deployed container. If the app inside the container uses Sprockets gem with default settings, then in the assets folder it has two manifest files. The app chooses [random one](https://github.com/rails/sprockets/blob/main/lib/sprockets/manifest_utils.rb#L44), unless it is [specified](https://github.com/rails/sprockets-rails/blob/master/lib/sprockets/railtie.rb#L215) explicitly.

From the end-user perspective it looks like no new assets were deployed.

The fix is simple:

```ruby
# config/environments/production.rb

config.assets.manifest = Rails.root.join('config', 'manifest.json')
```

I am not sure if the issue is worth mentioning in `config/deploy.yml` comments. At least I've posted it here.

**Comment by milk1000cc** [comment]
I encountered the same problem. Thanks for the solution.
