### ISSUE TITLE
When remove image: Error response from daemon: No such container: traefik

### ISSUE THREAD

**Issue by abratashov** [basecamp/kamal#629]
In the previous issue with incorrect deployment https://github.com/basecamp/kamal/issues/628 I try to remove the image, but get an error `No such container: traefik`:

```sh
$ kamal remove
  INFO [f88a63d8] Running /usr/bin/env mkdir -p .kamal on 31.42.190.196
  INFO [f88a63d8] Finished in 1.368 seconds with exit status 0 (successful).
Acquiring the deploy lock...
This will remove all containers and images. Are you sure? [y, N] (N) y
  INFO [fde74634] Running docker container stop traefik on 31.42.190.196
Releasing the deploy lock...
  ERROR (SSHKit::Command::Failed): Exception while executing on host 31.42.190.196: docker exit status: 1
docker stdout: Nothing written
docker stderr: Error response from daemon: No such container: traefik
```

**Comment by modusss** [comment]
After I removed I'm getting this error message to deploy a new one:

> $ kamal traefik reboot  
>   INFO [98405793] Running /usr/bin/env mkdir -p .kamal on 37.27.23.22
>   INFO [98405793] Finished in 3.636 seconds with exit status 0 (successful).
> Acquiring the deploy lock...
>   INFO [b89885a1] Running docker login ghcr.io -u [REDACTED] -p [REDACTED] on 37.27.23.22
>   INFO [b89885a1] Finished in 1.407 seconds with exit status 0 (successful).
>   INFO [465663b3] Running docker container stop traefik on 37.27.23.22
> Releasing the deploy lock...
>   ERROR (SSHKit::Command::Failed): Exception while executing on host 37.27.23.22: docker exit status: 1
> docker stdout: Nothing written
> docker stderr: Error response from daemon: No such container: traefik
