### ISSUE TITLE
Support --skip-push for setup command

### ISSUE THREAD

**Issue by wenderjean** [basecamp/kamal#659]
### Use case
We have a couple of services we want to deploy using Kamal but we don't want to keep deployment configuration files into the services' repository avoiding unnecessary dependencies. Currently our CI is responsible for building/pushing a new image to our registry and we're gonna use an "after push" event to trigger Kamal to deploy using `--skip-push`.

It seems like the main issue blocking this approach at the moment is the fact we're not able to setup a new server instance, `kamal setup` raises a couple of failures related to the `Dockerfile` and the registry itself. In fact, the entire setup process seems not transactional which means that even raising these errors I can proceed to `kamal deploy` that Docker is gonna be installed but, it is that kind of error we're gonna need to repetitively explain like "this is expected" 😝

Do you guys have plans to add such functionality? I noticed there is a  PR opened to that already
https://github.com/basecamp/kamal/pull/558

Or the way to go is making sure I have Docker and envs already loaded in the host then proceeding with `deploy --skip-push` only?

**Comment by vandot** [comment]
@wenderjean aren't
- `kamal server bootstrap` - Set up Docker to run Kamal apps
- `kamal env push` - Push the env file to the remote hosts
enough?

**Comment by wenderjean** [comment]
It is actually engouh @vandot.

For future reference I'm able to set everything up using `kamal server bootstrap --config-file=config/deploy.<environment>.yml`, `kamal envify` + `kamal env push`.

Anyway, the `bootstrap` command would probably deserver a section to it in official documentation.
