### ISSUE TITLE
Kamal requires deploy.yml even when using explicit destination with -d

### ISSUE THREAD

**Issue by cosmin-marginean** [basecamp/kamal#682]
We have the following deploy config files:
 * `deploy.test.yml`
 * `deploy.prod.yml`
 
and respective env files
* `.env.test`
* `.env.prod`

We only deploy to one or the other by using the explicit `-d` (destination) argument
```
kamal server bootstrap -d test
kamal env push -d test
kamal deploy -d test
```

We expect Kamal to only load the `deploy.<DESTINATION>.yml`, but it seems to be needing a `deploy.yml` as well, because we get the following error without it. All 3 commands above fail even when run individually and no `deploy.yml` is present.
```
 ERROR (RuntimeError): Configuration file not found in [REDACTED]/config/deploy.yml
```

This is a bit worrying because it's not clear why this file is needed or being loaded for. We are in a situation where both `test` and `prod` are identical (we use env vars to customize it) so we can create a 3rd `deploy.yml` with the same content just to get this to run.

But I can imagine people having `deploy.<DESTINATION>.yml` files which are substantively different, and being concerned about what should be in a `deploy.yml` and how that's being used in either case.

**Comment by ruyrocha** [comment]
It seems `destination` is `missing` in your case, and that would justify the exception. Please just hold on for a few while I'm checking into this issue.

**Comment by ruyrocha** [comment]
@cosmin-marginean it seems that you'll need to [set the configuration file](https://github.com/basecamp/kamal/blob/aea55480adcaf61e3eebfd49f2b8c039207ad0de/lib/kamal/cli/base.rb#L20) on command line if you're using different files on different environments, otherwise it's using the default value (`./config/deploy.yml`) and you'll always face that exception. Can you please give it a try?

**Comment by cosmin-marginean** [comment]
I've tried this below, because I need the `-d` to pick up the right .env file, but it fails
```
kamal env push -c config/deploy.test.yml -d test
...
ERROR (RuntimeError): Configuration file not found in [REDACTED]/config/deploy.test.test.yml
```
It seems to search for `deploy.test.test.yml` which is likely caused by `-d test` _on top_ of `-c`.

Then this one fails as well, as the `-c` seems to override the `-d`
```
kamal env push -c config/deploy.yml -d test
...
ERROR (RuntimeError): Configuration file not found in [REDACTED]/config/deploy.yml
```


This one "works" in the sense that it doesn't fail with that error, but the correct `.env` is not being picked up (because of the lack of `-d` I'm assuming).
```
kamal env push -c config/deploy.test.yml
```

In any case, the behaviour of `-d`, according to [this](https://github.com/basecamp/kamal/blob/aea55480adcaf61e3eebfd49f2b8c039207ad0de/lib/kamal/cli/base.rb#L21) is that it picks up the right deploy.xxx.yml, which is what we'd expect. It _also_ picks up the right .env file, which is documented separately [here](https://kamal-deploy.org/docs/configuration) (See "Using a generated .env file").

This would make the need for a `-c` superfluous in this particular case, or one should take precedence over the other. Either way, it seems that the behaviour of `-c` and `-d` need to be aligned/reconsidered?

**Comment by cosmin-marginean** [comment]
Ok, so in my base `deploy.yml` I have nothing but
```
require_destination: true
``` 

This seems to do the trick, so it's probably worth documenting this. I think there is still confusion around why a `deploy.yml` would be loaded at all, when we specify `-d test`. It would also be good to know whether settings in `deploy.test.yml`, for example, would override `deploy.yml`? In which case this would make sense, but I can't tell if that's the intention.

There's then the usecase when we only need one `deploy.yml` and different `.env` files (`.env.test`, `.env.prod`, etc). This would be useful, but it isn't possible because as soon as you specify `-d test` it needs a `deploy.test.yml` AND a `deploy.yml` :)

So I still feel like we're going around in circles, but at least I know how to work around it for now, and I appreciate your help!.

**Comment by nickhammond** [comment]
> It would also be good to know whether settings in deploy.test.yml, for example, would override deploy.yml? In which case this would make sense, but I can't tell if that's the intention.

They do. Your destination specific file gets applied last. This is helpful so that you can supply common deploy options in `deploy.yml`(service, image, registry, etc.),  and then destination-specific options within `deploy.test.yml`. This layering definitely comes from the Rails and Capistrano world since they  behave pretty similarly with environments. 

Do you have a completely different flow to deploy to test vs. production?

**Comment by cosmin-marginean** [comment]
@nickhammond Yes, that makes sense, thank you for confirming.

> Do you have a completely different flow to deploy to test vs. production?

No, they're identical (just the `.env`s are different) and that's what I was trying to figure out, in order to minimise the number of duplicate content here.
From what I've seen a `deploy.test.yml` is required when using `-d test` as much as `deploy.yml`, even when we set `require_destination: false`. (And we need `-d test` to load `.env.<destination>` so that can't be avoided)

So the `deploy.<destination>.yml` files need to exist, and unfortunately, they can't be empty either (assuming the `deploy.yml` contains all the config we need). Leaving us with the only option to have:

1. A `deploy.yml` that only has `require_destination: true` (this can't be empty either)
2. A `deploy.<destination>.yml` for each of the destinations, which are identical/duplicate.

So I guess the use case is that we need different `.env.<destination>`, but we don't need different `deploy.<destination>.yml`. Having `deploy.<destination>.yml` present but empty (in case we want to override something in the future) is a reasonable compromise, but that's not possible.

**Comment by nickhammond** [comment]
@cosmin-marginean You can have an empty `deploy.<destination>.yml` by just putting `{}` in that file. Or anything that Ruby can easily parse into a hash from YAML. This would let you do the last part that you're mentioning while still loading the specific `.env.destination` file.

**Comment by cosmin-marginean** [comment]
Ah, that is grand, I didn't know that! It works fine, thank you so much!

**Comment by nickhammond** [comment]
@cosmin-marginean Enjoy! Can this be closed?

**Comment by cosmin-marginean** [comment]
Yep, closing. Thank you all for your help
