### ISSUE TITLE
KAMAL_VERSION, pushed docker images, and deploy hooks

### ISSUE THREAD

**Issue by netshade** [basecamp/kamal#690]
I'm currently setting up a Kamal based infrastructure, and I've run into the following situation:

I have a "basic" Kamal setup that is pushing images to an ECR repo. In the push phase, I see an output like this:

```
 DEBUG [d4240817] 	#8 pushing manifest for MY_REGISTRY/MY_IMAGE:b6d827f9f7015b5f0ddc96b9ad026dba3b4f0d42_uncommitted_0ede4dab9b33bc88@sha256:56979f1bc6c719e7e30ca89cb31edd3991a2f0cbbef8e230aea1075a7cea228b
 DEBUG [d4240817] 	#8 pushing manifest for MY_REGISTRY/MY_IMAGE:b6d827f9f7015b5f0ddc96b9ad026dba3b4f0d42_uncommitted_0ede4dab9b33bc88@sha256:56979f1bc6c719e7e30ca89cb31edd3991a2f0cbbef8e230aea1075a7cea228b 1.2s done
```

Notably, the image tag in this case is `b6d827f9f7015b5f0ddc96b9ad026dba3b4f0d42_uncommitted_0ede4dab9b33bc88`.

Also in my setup, I have a pre-deploy hook. One of the tasks of this pre-deploy hook is acquire the image that was just pushed on a separate machine under my control. My reading of the hooks was that I could assume that the `KAMAL_VERSION` being passed to this hook would be the same as the value of that image tag above ( namely: `b6d827f9f7015b5f0ddc96b9ad026dba3b4f0d42_uncommitted_0ede4dab9b33bc88` ). However, I am inconsistently seeing failures where the `KAMAL_VERSION` being passed to that script is different from that used to tag the image.

The inconsistency makes me think that perhaps there are changes to the filesystem taking place that causes the `KAMAL_VERSION` to be recomputed at the time of hook execution. Is this how should Kamal "should" work? eg, should I expect `KAMAL_VERSION` to potentially change over the course of a given Kamal command execution? Or is this a bug?

**Comment by netshade** [comment]
I should note, btw, that the differences in `KAMAL_VERSION` is the component *after* the `uncommitted` marker. That is to say, the docker tag looks like:

`MY_IMAGE:H1_uncommitted_H2`

and the `KAMAL_VERSION` passed to the hook looks like:

`MY_IMAGE:H1_uncommitted_H3`

**Comment by netshade** [comment]
After some further work on this, I should note that this appears to happen during the deploy that occurs during `kamal setup`. `kamal deploy` appears? to be stable.

**Comment by yanguango** [comment]
I'm seeing the same issue, the KAMAL_VERSION is like xxx_uncommitted_xxx, my guess is the git directory has some changes are not committed, and kamal detects it and then adds it in the version tag. 
https://github.com/basecamp/kamal/blob/e8b9f8907f16416accb47ba2208185f1ea91754b/lib/kamal/cli/build.rb#L23

**Comment by netshade** [comment]
I looked into this further, and it appears that when `Kamal::Configuration` encounters uncommitted changes, it tries to create a "random" hash via [`SecureRandom.hex(8)`](https://github.com/basecamp/kamal/blob/main/lib/kamal/configuration.rb#L332). If the configuration was stable across the execution, this would probably be fine, but I think what appears to be happening during setup is that a different configuration is used to populate `KAMAL_VERSION` during the `pre-deploy` hook than what is used to actually push the image. I'm not sure the ordering on dependencies there, but that "feels" like what the bug probably is. :-p

Idk if it makes sense to fix the ordering problem here, or to change it such that the uncommitted hash is "honest"? Something like, 

`git status --porcelain | awk '{print $2}' | xargs -I{} md5sum {} | md5sum | awk '{print $1}'` , computing a hash of hashes of all uncommitted files? It seems a bit heavyweight, but also, at least more true to what the intent is rather than a random number?

**Comment by morgoth** [comment]
@netshade There was a change https://github.com/basecamp/kamal/pull/700 that may solve your issue as there should no more be "uncommited" part in the version.
Can you please verify and eventually close the issue?

**Comment by netshade** [comment]
That change works for me, w/ the absence of the `uncommitted` portion. Thanks.
