### ISSUE TITLE
post-deploy hook with curl does not work because curl is not available

### ISSUE THREAD

**Issue by dimitri-koenig** [basecamp/kamal#761]
Hi guys

Somehow I get a `curl: not found` error with the basic post-deploy example. Seems like the base image of ruby does not contain curl, and the post-deploy hook is run from within the kamal image and not the host server.

My workaround right now is to extend the kamal image and install curl afterwards.

Is there another way to use curl in post-deploy hook? Or is this a bug?

**Comment by dimitri-koenig** [comment]
I'm not talking about curl/wget ON the server, but IN the kamal docker image. That's the current place where the post-deploy hook is executed.

**Comment by dhh** [comment]
Ensuring the tools required by your hooks are available in the image you're using is an exercise left to the programmer. Adding curl as a package as part of your Dockerfile is the correct solution.
