### ISSUE TITLE
Docker Error on local machine: no space left on device

### ISSUE THREAD

**Issue by abratashov** [basecamp/kamal#765]
After the deployment of several projects with Kamal, I've been stuck on my local machine with the error `no space left on device`:
```sh
kamal setup -d stage
...
#39 pushing layers
#39 pushing layers 0.4s done
#39 ERROR: failed to push registry.gitlab.com/myuser/my-project/my-project-stage:f09ead605afe2604b1e529a97994f90c7eec39f9_uncommitted_82ad302c95ac8ff8: write /home/myuser/.docker/.token_seed: no space left on device
------
 > exporting to image:
------
ERROR: failed to solve: failed to push registry.gitlab.com/myuser/my-project/my-project-stage:f09ead605afe2604b1e529a97994f90c7eec39f9_uncommitted_82ad302c95ac8ff8: write /home/myuser/.docker/.token_seed: no space left on device
```

On my local machine, only 75MB of free space was left:
```sh
user@local_machine$ df -h /
Filesystem      Size  Used Avail Use% Mounted on
/dev/nvme0n1p2  468G  444G   75M 100% /
```

After exploring disk capacity, I've found a lot of ~40GB volumes of projects that I'd deployed before:
```
sudo du -h --max-depth=1 /var/lib/docker/volumes | sort -h
...
5,0G  /var/lib/docker/volumes/buildx_buildkit_kamal-kamal-blog-staging-multiarch0_state
6,8G  /var/lib/docker/volumes/buildx_buildkit_kamal-kamal-blog-stage-multiarch0_state
23G /var/lib/docker/volumes/buildx_buildkit_kamal-my-project-stage-multiarch0_state
37G /var/lib/docker/volumes/buildx_buildkit_kamal-kamal-blog-multiarch0_state
44G /var/lib/docker/volumes/buildx_buildkit_kamal-my-project-demo-multiarch0_state
45G /var/lib/docker/volumes/buildx_buildkit_kamal-my-project-demo-multiarch0_state
160G  /var/lib/docker/volumes
```
As I see, the cause is this open Docker issue https://github.com/docker/for-linux/issues/1423
I've found a workaround in this comment https://github.com/docker/for-linux/issues/1423#issuecomment-1958990802

Removing folders freed up space, but it corrupts the build's registry and Docker has to be fully re-installed! :-1: 

After the painful reinstalling Docker, I've found in the [docs](https://kamal-deploy.org/docs/commands/build/) the correct way to remove the builds:
```sh
kamal build remove -d stage
```
Also, I've disabled `multiarch` building that enormously speeds up the time of image re-building, because my local machine and the remote host have the same AMD64 architecture (this nice feature was added in the version `1.4.0`):
```sh
# https://kamal-deploy.org/docs/configuration/builders/#using-native-builder-when-multi-arch-isnt-needed
builder:
  multiarch: false
```

So, I'm closing this ticket!

**OS**: Ubuntu 22.04.4 LTS
**Docker**: 24.0.5, build 24.0.5-0ubuntu1~22.04.1
**Kamal**: 1.4.0

**Comment by mrhaddad** [comment]
How did you resolve this issue? I'm having to manually run `kamal server exec "docker system prune -a -f"` relatively often which I imagine is … wrong.

**Comment by abratashov** [comment]
@mrhaddad I haven't had such an issue again, but as I mentioned above there is a [command](https://kamal-deploy.org/docs/commands/build/):
```sh
kamal build remove -d demo
```
Also, you can ask in Discord [channel](https://discord.gg/YgHVT7GCXS)
