### ISSUE TITLE
Host Changes in Builder Config Do Not Apply Automatically

### ISSUE THREAD

**Issue by zdehasek** [basecamp/kamal#806]
After changing the configuration file `./config/deploy.yml` from:

```
...
builder:
  remote:
    arch: amd64
    host: ssh://root@<old_ip_address>
...
```
to

```
...
builder:
  remote:
    arch: amd64
    host: ssh://root@<new_ip_address>
...
```
Kamal did not update the Docker Buildx or context configurations, so the build process continued to attempt to reach <old_ip_address>.

After removing the specific Docker Buildx instance and Docker context, and re-running kamal deploy, Kamal successfully re-created the builder configuration.

**Comment by djmb** [comment]
I think this is the same as https://github.com/basecamp/kamal/issues/714
