### ISSUE TITLE
Traefik renew letsencrypt certificates

### ISSUE THREAD

**Issue by kenzo2013** [basecamp/kamal#836]
Hi guys,

How can I renew manually and automatically letsencrypt with traefik?

Please help

**Comment by k3vout** [comment]
Hi @kenzo2013, did you find out?

**Comment by k3vout** [comment]
In my case, I had to open port 80 on Hetzner to renew the certificate.
https://community.letsencrypt.org/t/solved-acme-traefik-no-new-certificates-are-generated/190750/2

**Comment by kenzo2013** [comment]
@k3vout I did this `kamal traefik restart`

**Comment by k3vout** [comment]
> @k3vout I did this `kamal traefik restart`

@kenzo2013, I tried that but it didn't work, opening the port worked for me. Thanks for your reply anyway.
