### ISSUE TITLE
Build failure: Docker image cannot be built due to missing Git submodules

### ISSUE THREAD

**Issue by fabiendv** [basecamp/kamal#848]
When attempting to build a Docker image that depends on a repository with Git submodules, the build process fails because the `git -C` command does not include the submodules.

### Actual Behavior

The git -C command does not automatically include submodules, leading to a build failure due to missing submodule content.

### Proposed Solution

Add an option to the git -C command that allows for the inclusion of submodules, similar to the --recurse-submodules flag available in other Git commands.

### Environment

Kamal version: 1.7.1

**Comment by djmb** [comment]
Thanks for reporting this @fabiendv! As a workaround, you can set the build context to `.` which will build directly from the checkout but will include any uncommited changes.

**Comment by fabiendv** [comment]
Thanks @djmb 

I confirm the following lines work:

```
builder:
  context: .
```

**Comment by djmb** [comment]
The original issue should be fixed by https://github.com/basecamp/kamal/pull/889
