### ISSUE TITLE
Is there any way to access a specific container?

### ISSUE THREAD

**Issue by marcuxyz** [basecamp/kamal#850]
Is there any way to access a specific container?

I created a container just to run a specific cron and I would like to access it.
Well, the account is not being executed correctly. Can anyone help me?

References: https://github.com/basecamp/kamal/issues/47

Thanks

**Comment by K4sku** [comment]
You can run `kamal app exec -i --reuse bash` to get interactive bash, apply `--hosts` or `--roles` filters if necessary. 
See `kamal app help exec` for details.

Or simply ssh to host and then do `docker exec -it <CONTAINER ID> /bin/bash` to access in-container bash.

You can get CONTAINER ID from `docker ps`, it's a first column.

**Comment by marcuxyz** [comment]
Hello @K4sku thank you for reply my question. I will go check this point
