### ISSUE TITLE
Asset is not present in Pipeline

### ISSUE THREAD

**Issue by Talha345** [basecamp/kamal#852]
There is a issue whenever I add a new image to the asset pipeline and deploy via Kamal, the server gives a 500 with the message `asset_name is not present in the asset pipeline.` Redeploying the same build the second time fixes the issue.

Rails version: 7.1.3
Ruby version: 3.2.2
Kamal version: 1.3

**Comment by K4sku** [comment]
Do you have `asset_path` set in deploy.yml?

**Comment by Talha345** [comment]
> Do you have `asset_path` set in deploy.yml?

Yes, I have the following in my deploy.yml:

`asset_path: /rails/public/assets`

**Comment by K4sku** [comment]
If you are using sprockets see this issue https://github.com/basecamp/kamal/issues/626

**Comment by morgoth** [comment]
@Talha345 does it solve your issue? Can it be closed?

**Comment by Talha345** [comment]
Yes I think it is fixed. This can be closed.
