### ISSUE TITLE
RubyZip 3.0 Warning Blocking Kamal Deploy

### ISSUE THREAD

**Issue by szluyufeng** [basecamp/kamal#855]
I'm running into an issue where my deployment with Kamal gets stuck because of this RubyZip warning. Here's the message:

`Post-install message from rubyzip:
RubyZip 3.0 is coming!
**********************

The public API of some Rubyzip classes has been modernized to use named
parameters for optional arguments. Please check your usage of the
following classes:
  * Zip::File
  * Zip::Entry
  * Zip::InputStream
  * Zip::OutputStream

Please ensure that your Gemfiles and .gemspecs are suitably restrictive
to avoid an unexpected breakage when 3.0 is released (e.g. ~> 2.3.0).
See https://github.com/rubyzip/rubyzip for details. The Changelog also
lists other enhancements and bugfixes that have been implemented since
version 2.3.0.`

I've made sure my Gemfiles and .gemspecs are set to ~> 2.3.0 to avoid any breakages, but the warning keeps appearing and it's blocking the whole deploy process. Is there something else I need to do to fix this, or should I be handling this differently?

Thanks for the help!

**Comment by acidtib** [comment]
whats the error message being triggered by the zip warning notice?

**Comment by szluyufeng** [comment]
> whats the error message being triggered by the zip warning notice?

There isn't an actual error message being generated, merely an indefinite stall occurring.

This issue mirrors the one previously highlighted in the following discussion: https://github.com/basecamp/kamal/discussions/747.
