### ISSUE TITLE
feat: adding support for docker capabilities

### ISSUE THREAD

**Issue by vveliev-tc** [basecamp/kamal#880]
Hello, I would like to request new feature to add option to pass docker runtime capabilities.

As example if I would like to use strace in docker container, container need to be started with 

```bash
docker run --cap-add=SYS_PTRACE "$@"
```

when adding option to Kamal i get an error that this is not supported:

deploy.yml
```yaml
cap_add:
  - SYS_PTRACE
```

ERROR:
```bash
  ERROR (Kamal::ConfigurationError): unknown key: cap_add
```	

More information available here: https://docs.docker.com/engine/reference/run/#runtime-privilege-and-linux-capabilities

**Comment by acidtib** [comment]
have you tried using the options field to pass the custom configuration

https://kamal-deploy.org/docs/configuration/roles/#custom-role-configuration

**Comment by vveliev-tc** [comment]
@acidtib thanks a lot! 

yes option does work, it just was not obvious that option is used for additional docker parameters. 

what is the logic behind splitting docker commands? like [cmd, logger, image] are available in similar syntax like docker-compose but for, [user, cap_add] it's need to go under `options` ?

**Comment by nzwsch** [comment]
FYI

```yaml
servers:
  web:
    hosts:
      - example.com
    options:
      "cap-add":
        - SYS_ADMIN
```
