### ISSUE TITLE
dotenv version is too old

### ISSUE THREAD

**Issue by alec-c4** [basecamp/kamal#899]
Hey!
One more problem - `dotenv` version is too old.If you add kamal to your `Gemfile` you'll be unable to use newer version of dotenv gem in case of any. 
https://github.com/basecamp/kamal/blob/ec4aa4585278757302e592a2fc12fbf7e14f7b90/kamal.gemspec#L18C1-L18C41

Current version https://github.com/bkeepers/dotenv is 3.1.2

**Comment by igor-alexandrov** [comment]
Hi Alex, while we deal with `dotenv` version, you can use Kamal without adding it to the Gemfile.

To do this create a separate `.kamal/Gemfile`

```
source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby file: ".ruby-version"

gem "kamal", "~> 1.8"
```

**Comment by alec-c4** [comment]
@igor-alexandrov hey! It is a good idea, but looks like a workaround. From my point of view it is important to keep deps updated, am I wrong?

**Comment by igor-alexandrov** [comment]
Yes, deps should be kept up to date. I update `dotenv`.
At the same time, my approach is not a workarond. Kamal depends from `activesupport >= 7.0` and I use it to deploy Rails 6 and Rails 5 apps.

**Comment by igor-alexandrov** [comment]
@djmb this can be closed it seems.
