### ISSUE TITLE
When I run kamal app logs -f, two lines of dates appear. Is there a way to remove one of them?

### ISSUE THREAD

**Issue by activeliang** [basecamp/kamal#910]
As shown in the image, when I follow the logs, I noticed that the executed command includes the --timestamps flag, which causes the logs to display duplicate dates. I understand this might be useful for programs other than Rails that don't include timestamps in their logs, but for Rails logs that already have timestamps, it results in redundancy. Is there an option to disable this?

![WX20240822-202059@2x](https://github.com/user-attachments/assets/2d31ad22-d109-46ec-b3ff-e6902f4359b9)

**Comment by djmb** [comment]
An option to skip the docker timestamps was added here - https://github.com/basecamp/kamal/pull/958
