### ISSUE TITLE
Support Earthly builder

### ISSUE THREAD

**Issue by brandonkal** [basecamp/kamal#911]
I use [Earthly - Make Builds Super Simple](https://earthly.dev/) to build images remotely with caching. It would be nice to be able to specify a command to call that builds the images.

**Comment by jeremy** [comment]
There are lots of image builders out there. Overriding a single command invocation will be insufficient for most. Those that integrate with mainline Docker and BuildKit should "just work," though.

Recommend checking out native caching support: https://kamal-deploy.org/docs/configuration/builders/#builder-cache

**Comment by brandonkal** [comment]
Earthly performs image builds in Buildkit. But kamal wants a Dockerfile.

So it is a deployment tool that requires Docker on the host that runs kamal which would be unfortunate. Is there no support for building images outside of kamal (ie in CI with unit and integration tests that must pass before it is pushed to to production registry?

**Comment by jeremy** [comment]
Consider pre-building the image with Earthly, tag it as Kamal would, and then `kamal deploy --skip-push` (or `skip_push: true` in config). May get you what you're looking for!
