### ISSUE TITLE
Issue: Kamal Not Loading `.env` When Deploying NextJS App

### ISSUE THREAD

**Issue by diogoparente** [basecamp/kamal#925]
First off, huge kudos for Kamal— I'm really enjoying its simplicity and value so far!

### Context

I'm currently working on deploying a Next.js application to a VPS using Kamal and have been following some tutorials closely:

- [Deploying NextJS using Mrsk](https://medium.com/@ruslanfg/deploying-nextjs-using-mrsk-819aa9eb83ba)
- [Deploy Next.js with Kamal](https://getdeploying.com/deploy-nextjs)
- [Self-host Next.js with Hetzner and Kamal](https://logsnag.com/blog/self-host-nextjs-hetzner-kamal)

Everything works fine when building and running the app locally via Docker, but when attempting to deploy via Kamal to my VPS, I hit an issue with `.env` files not being loaded.

### The Problem

When building locally, Docker runs perfectly fine, and I'm able to run the app without issues. However, when using Kamal, it appears that the `.env` file is not being loaded correctly during the build.

I've tried the following approaches to no avail:
- `kamal envify` with the `.env.erb`
- `kamal env push` with an exact `.env` copy

My `.env` file has all the necessary values as mentioned in my `config.yml`, and it works locally, but not during Kamal-based deployment.

### Environment

- Docker builds and runs locally: ✅
- Kamal `.env` handling: ❌

### Screenshots

To provide more context, here are some logs/screenshots:

![image](https://github.com/user-attachments/assets/b9a7e811-0b64-4989-96c2-320ac6c94ce3)
<img width="543" alt="Screenshot 2024-09-05 at 18 37 52" src="https://github.com/user-attachments/assets/cacb3abb-8535-4a2e-b808-c2215e6d3cd5">
<img width="457" alt="Screenshot 2024-09-05 at 18 40 27" src="https://github.com/user-attachments/assets/0f5f0160-b955-4dd7-8a7f-bd64e99c611c">

Has anyone encountered this issue before or could offer advice on how to ensure Kamal properly loads `.env` during deployment?

Thanks in advance for any pointers!

**Comment by djmb** [comment]
Hi @diogoparente!

The `env` section is for when the app is being run, rather than when it's being built.

You'll need to pass the secrets via the builder section:

```
builder:
  secrets:
    - CLERK_SECRET_KEY
  args:
    NEXT_PUBLIC_CLERK_PERISHABLE_KEY: something
```

**Comment by diogoparente** [comment]
> Hi @diogoparente!
> 
> 
> 
> The `env` section is for when the app is being run, rather than when it's being built.
> 
> 
> 
> You'll need to pass the secrets via the builder section:
> 
> 
> 
> ```
> 
> builder:
> 
>   secrets:
> 
>     - CLERK_SECRET_KEY
> 
>   args:
> 
>     NEXT_PUBLIC_CLERK_PERISHABLE_KEY: something
> 
> ```

Sweet, I'll give it a try!

Thanks for the help

**Comment by jericopulvera** [comment]
I'm having the same issue and the above solution is not working for me. I'm running `kamal setup` command

**Comment by jericopulvera** [comment]
Update: The issue is that the next build requires the .env file, and locally deploying it can only be included when it's either committed on Git or when build context is set to "context: ." . https://kamal-deploy.org/docs/configuration/builders/#build-context

**Comment by Cytla24** [comment]
> Update: The issue is that the next build requires the .env file, and locally deploying it can only be included when it's either committed on Git or when build context is set to "context: ." . https://kamal-deploy.org/docs/configuration/builders/#build-context

you cooked right here. this worked for me. ty

**Comment by Derick1530** [comment]
> Update: The issue is that the next build requires the .env file, and locally deploying it can only be included when it's either committed on Git or when build context is set to "context: ." . https://kamal-deploy.org/docs/configuration/builders/#build-context

on my side I am running kamal commands in a git action, same configuration  or something to change worth mentioning ?

**Comment by alexandrule** [comment]
> Update: The issue is that the next build requires the .env file, and locally deploying it can only be included when it's either committed on Git or when build context is set to "context: ." . https://kamal-deploy.org/docs/configuration/builders/#build-context

@jericopulvera It works! Thanks!
