### ISSUE TITLE
Support for blue/green deployments or workarounds

### ISSUE THREAD

**Issue by mkote** [basecamp/kamal#941]
Hello Kamal team,

I'm currently evaluating Kamal for managing the deployment process of a web application. My goal is to implement blue/green deployments where I can deploy a new version of my application to the same server hosts, but delay traffic routing (via Traefik) to the new version until I've manually verified its functionality. 

**Desired Flow**

Ideally, I'd like to run something like:

```bash
kamal deploy --no-update
```

This would deploy the new version of my app without switching Traefik over to it. Once I'm satisfied with the new version (after running manual tests or verification steps), I'd like to trigger Traefik to switch traffic over to the new version with a command such as:

```bash
kamal deploy --promote
```

An alternative approach could involve using the healthcheck mechanism where my containers would wait for a manual promotion signal (e.g., the creation of a specific file). For example:

```bash
kamal app exec --reuse --version <new-version> "touch /tmp/promoted"
```

This could trigger a healthcheck that would then promote the new version once the /tmp/promoted file exists on the containers.

I've experimented with this idea and while this approach seems to work for holding off on marking the new version as healthy, there’s one major blocker:

I’m unable to access the new containers externally while the healthcheck is pending. For my use case, it would be ideal to access these containers from outside (without Traefik flipping traffic) to verify the application before promoting it to production.

Would it be possible to implement support for this type of deployment flow in Kamal? Some ideas include:

    A --no-update flag for kamal deploy that deploys a new version without affecting Traefik's routing.
    A --promote or similar command that could be run after manual verification to complete the deployment and switch traffic over.
    Access to the newly deployed containers for manual inspection or verification before promoting them live.

I'd love to hear your thoughts or potential workarounds.

Best regards

**Comment by jeremy** [comment]
This is coming via "rollout" support in Kamal 2 with kamal-proxy. You'd deploy your new version to rollout, set a kamal-rollout cookie in your health-checking requests to target the rollout container, then do a full deploy of the new version when satisfied all is well.
