### ISSUE TITLE
ActiveSupport::MessageEncryptor::InvalidMessage: while upgrading to kamal 2.0

### ISSUE THREAD

**Issue by deepakmahakale** [basecamp/kamal#985]
It seems while upgrading from 1.x there's 2.0 it's not able to read the master key.

```
ActiveSupport::MessageEncryptor::InvalidMessage:
```

**Comment by kobaltz** [comment]
After you run `kamal init` with kamal 2.0, make sure that you go under `.kamal/secrets` and point the variable to the master key. Make sure that you don't put the plain text key in here like you would do the `.env` file because this secrets file is more of a mapper and will get committed to your version control.

**Comment by deepakmahakale** [comment]
It took me 2 hours to realise I had to use `config/credentials/production.key` since I am using environment specific credentials.

I also had to add the following:

`config/deploy.yml`
```yml
<% require "dotenv"; Dotenv.load(".env") %>

# Name of your application. Used to uniquely configure containers.
.
.
```

`.kamal/secrets`

```ruby
KAMAL_REGISTRY_PASSWORD=$KAMAL_REGISTRY_PASSWORD
RAILS_MASTER_KEY=$(cat config/credentials/production.key)
```

**Comment by santy18** [comment]
> It took me 2 hours to realise I had to use `config/credentials/production.key` since I am using environment specific credentials.
> 
> I also had to add the following:
> 
> `config/deploy.yml`
> 
> ```yaml
> <% require "dotenv"; Dotenv.load(".env") %>
> 
> # Name of your application. Used to uniquely configure containers.
> .
> .
> ```
> 
> `.kamal/secrets`
> 
> ```ruby
> KAMAL_REGISTRY_PASSWORD=$KAMAL_REGISTRY_PASSWORD
> RAILS_MASTER_KEY=$(cat config/credentials/production.key)
> ```

Bro... thank you thank you thank youuuu
