### ISSUE TITLE
Unable to perform Host header checking with kamal-proxy health checks

### ISSUE THREAD

**Issue by karls** [basecamp/kamal#992]
Hi team,

I deployed a Django app with Kamal 2.0 today. It was smooth sailing apart from one issue which I couldn't work out and had to work around.

It seems like when kamal-proxy is performing health-checks when a new version of the service is deployed and started, it uses the container's name in the Host header. Django has a setting for [safelisting host/domain names](https://docs.djangoproject.com/en/5.1/ref/settings/#allowed-hosts) (to prevent Host header attacks). In production, I'd set it to the domain(s) of my app, but in doing so, it causes the health-checks to fail with the following:

```py
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '7c7168a662c1:8000'. You may need to add '7c7168a662c1' to ALLOWED_HOSTS.
```

I tried getting the container's name inside the Django app settings, using `socket.gethostname()` etc, but to no avail. The hostname returned by any of the Python hostname-getting-functions are always different from the name included in the above exception.

For instance, for the above exception the hostname reported by `socket.gethostname()` when the app was booting up was `<server IP>-85671408975f`.

**Comment by julianrubisch** [comment]
Actually the same is true for any Rails app, but there's a setting in `config/production.rb` you can uncoment:

```rb
  config.host_authorization = { exclude: ->(request) { request.path == "/up" } }
```

is there something similar you can do in Django?

**Comment by karls** [comment]
Got it. There isn't anything as simple as this in Django AFAICT.

But one can write a tiny custom middleware module to deal with this. Here's what I ended up doing.

```py
# <project>/middleware.py

from django.http import HttpResponse


class HealthCheckMiddleware:
    def __init__(self, get_response):
        self.get_response = get_response

    def __call__(self, request):
        if request.path == "/up/":
            # Or perform any "real" health checking, if needed
            response = HttpResponse("OK")
        else:
            response = self.get_response(request)

        return response
```

Then, in the MIDDLEWARE setting, add the new `HealthCheckMiddleware` as the first item in the list, which will circumvent Django's built-in security middleware that deals with checking allowed hosts, among other things. All other paths apart from `/up/` are processed and move through the middleware chain normally.

```py
# <project>/settings.py

if not DEBUG:
  ALLOWED_HOSTS = ["<your production domain(s)"]
  CSRF_TRUSTED_ORIGINS = [f"https://{host}" for host in ALLOWED_HOSTS]

MIDDLEWARE = [
    "<project>.middleware.HealthCheckMiddleware",
    "django.middleware.security.SecurityMiddleware",
    # rest of the Django middleware
]
```

All-in-all, a bit more wordy than the Rails equivalent, but works nonetheless.

**Comment by voberoi** [comment]
@karls I just ran into this issue, thanks for sharing a solution.

**Comment by naveencom** [comment]
> Got it. There isn't anything as simple as this in Django AFAICT.
> 
> But one can write a tiny custom middleware module to deal with this. Here's what I ended up doing.
> 
> ```python
> # <project>/middleware.py
> 
> from django.http import HttpResponse
> 
> 
> class HealthCheckMiddleware:
>     def __init__(self, get_response):
>         self.get_response = get_response
> 
>     def __call__(self, request):
>         if request.path == "/up/":
>             # Or perform any "real" health checking, if needed
>             response = HttpResponse("OK")
>         else:
>             response = self.get_response(request)
> 
>         return response
> ```
> 
> Then, in the MIDDLEWARE setting, add the new `HealthCheckMiddleware` as the first item in the list, which will circumvent Django's built-in security middleware that deals with checking allowed hosts, among other things. All other paths apart from `/up/` are processed and move through the middleware chain normally.
> 
> ```python
> # <project>/settings.py
> 
> if not DEBUG:
>   ALLOWED_HOSTS = ["<your production domain(s)"]
>   CSRF_TRUSTED_ORIGINS = [f"https://{host}" for host in ALLOWED_HOSTS]
> 
> MIDDLEWARE = [
>     "<project>.middleware.HealthCheckMiddleware",
>     "django.middleware.security.SecurityMiddleware",
>     # rest of the Django middleware
> ]
> ```
> 
> All-in-all, a bit more wordy than the Rails equivalent, but works nonetheless.

@karls How should ALLOWED_HOSTS look ?

I'm still facing this issue.

**Comment by karls** [comment]
@naveencom `ALLOWED_HOSTS` should contain your app's production URL(s). For the purposes of health-checking it doesn't matter too much what's in there, because the custom middleware will prevent the health-check request from reaching the point at which Django performs the security check that looks at `ALLOWED_HOSTS`.

Make sure that:

1. The health-check path in the proxy config in `config/deploy.yml` is set up to make a request to the _same_ path as in the custom middleware
2. The middleware is inserted _before_ Django's `SecurityMiddleware`

For example:

```yaml
# config/deploy.yaml

proxy:
  host: <yourproductiondomain.com>
  app_port: <the port your web server is listening on>
  healthcheck:
    path: '/health-check/'
```

```py
# <project>/middleware.py

from django.http import HttpResponse


class HealthCheckMiddleware:
    def __init__(self, get_response):
        self.get_response = get_response

    def __call__(self, request):
        if request.path == "/health-check/":
            # Or perform any "real" health checking, if needed
            response = HttpResponse("OK")
        else:
            response = self.get_response(request)

        return response
```

Or post your code/stacktrace/errors if this doesn't help and we'll figure it out.

**Comment by naveencom** [comment]
@karls Fixed the issues. Thanks.

**Comment by gaultierq** [comment]
> host: <yourproductiondomain.com>

In my understanding, during a new deployment, this health check will verify the currently running container is up. This could result in a false positive and lead to deploying a faulty application.

**Comment by karls** [comment]
Could you explain further — how could this result in a false positive and what do you mean by a faulty application? Faulty how?

**Comment by gaultierq** [comment]
Sure! 

If a web application is healthy and running in the `web-1` container, accessible at `yourproductiondomain.com`, when a new version is deployed, Kamal will start a new container, `web-2`, and check its health by verifying that `web-2/up` returns a 200 status. If the health check is successful, it will then redirect traffic from web-1 to web-2.

However, if web-2 contains faulty code and the up endpoint does not return a 200 status, Kamal should abort the deployment and not redirect the traffic. 

By setting host: <yourproductiondomain.com>, Kamal will check the health by sending an HTTP request to `yourproductiondomain.com/up`, which will be handled by web-1, since during the deployment, the proxy is still redirecting requests to the running container. And the deployment will be successful although the web-2 container is not healthy.

Please let me know if I am missing something.

**Comment by karls** [comment]
Got it. But I don't believe this is the case.

I think Kamal (kamal-proxy) will send healthchecks to the actual container instance (web-2), not `yourproductiondomain.com/up`. If it sent requests to `yourproductiondomain.com/up`, then there would not be any need for the `HealthCheckMiddleware` I outlined in my earlier comments as the requests would already have the correct Host header and would pass Django's security middleware without issues.

If `kamal-proxy` actually made requests to `yourproductiondomain.com/up` then I don't think there would be any way for it to say which container to direct the health check requests to. It wouldn't really be a health check at all as web-2 hasn't been swapped in as a traffic target yet and all health check requests would be handled by web-1.

The sequence of events, as far as I understand, is roughly the following:

1. a deploy happens by doing `kamal deploy`
2. `kamal-proxy` starts a new container with the new version of the code
3. `kamal-proxy` pings the new container's (not the production domain's) `/up/` path for checking the new container's health
4. once the new container responds with 200 OK, `kamal-proxy` switches the traffic target from web-1 to web-2
5. once web-1 is drained, `kamal-proxy` stops web-1

@kevinmcconnell can you confirm that my thought process correct?

**Comment by gaultierq** [comment]
oh yay it makes a lot more sense, thanks for sharing !
